
package telas.jinternalframe;
import listener.AlteraProdutoListener;

public class AlteraProduto extends javax.swing.JInternalFrame {
    //private FrmPrincipalListener listener = new FrmPrincipalListener(this);
    private AlteraProdutoListener listener = new AlteraProdutoListener(this);
    /**
     * Creates new form LojaCadastroProduto
     */
    public AlteraProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCadastroProdutos = new javax.swing.JPanel();
        PainelBotoes = new javax.swing.JPanel();
        BotaoGravar = new javax.swing.JButton();
        BotaoExcluir = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();
        PainelCamposdados1 = new javax.swing.JPanel();
        TXTCodigo = new javax.swing.JTextField();
        TXTNome = new javax.swing.JTextField();
        TXTMarca = new javax.swing.JTextField();
        TXTModelo = new javax.swing.JTextField();
        PainelCamposdados2 = new javax.swing.JPanel();
        LValorCusto = new javax.swing.JLabel();
        LValorUnitario = new javax.swing.JLabel();
        LQuantidade = new javax.swing.JLabel();
        TXTValorCusto = new javax.swing.JTextField();
        TXTValorUnitario = new javax.swing.JTextField();
        TXTQuantidade = new javax.swing.JSpinner();
        LCodigo = new javax.swing.JLabel();
        LNome = new javax.swing.JLabel();
        LMarca = new javax.swing.JLabel();
        LModelo = new javax.swing.JLabel();
        LDescricao = new javax.swing.JLabel();
        PTXTDescricao = new javax.swing.JScrollPane();
        TXTDescricao = new javax.swing.JTextArea();
        PainelLocalizar = new javax.swing.JPanel();
        TXTCodigoB = new javax.swing.JCheckBox();
        TXTNomeB = new javax.swing.JCheckBox();
        TXTSobrenomeB = new javax.swing.JCheckBox();
        TXTModeloB = new javax.swing.JCheckBox();
        TXTBusca = new javax.swing.JTextField();
        BotaoLocalizar = new javax.swing.JButton();
        PainelTabela = new javax.swing.JPanel();
        SPTabela = new javax.swing.JScrollPane();
        TabelaResultado = new javax.swing.JTable();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("telas/jinternalframe/Bundle"); // NOI18N
        PainelCadastroProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("AlteraProduto.PainelCadastroProdutos.border.title"))); // NOI18N

        BotaoGravar.setText(bundle.getString("AlteraProduto.BotaoGravar.text")); // NOI18N
        BotaoGravar.addActionListener(listener);
        BotaoGravar.setActionCommand("gravar");
        BotaoExcluir.setText(bundle.getString("AlteraProduto.BotaoExcluir.text")); // NOI18N
        BotaoExcluir.addActionListener(listener);
        BotaoExcluir.setActionCommand("excluir");
        BotaoCancelar.setText(bundle.getString("AlteraProduto.BotaoCancelar.text")); // NOI18N
        BotaoCancelar.addActionListener(listener);
        BotaoCancelar.setActionCommand("cancelar");
        javax.swing.GroupLayout PainelBotoesLayout = new javax.swing.GroupLayout(PainelBotoes);
        PainelBotoes.setLayout(PainelBotoesLayout);
        PainelBotoesLayout.setHorizontalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(BotaoGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BotaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        PainelBotoesLayout.setVerticalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoGravar)
                    .addComponent(BotaoExcluir)
                    .addComponent(BotaoCancelar))
                .addContainerGap())
        );

        TXTCodigo.setText(bundle.getString("AlteraProduto.TXTCodigo.text")); // NOI18N
        TXTCodigo.setEnabled(false);

        TXTNome.setText(bundle.getString("AlteraProduto.TXTNome.text")); // NOI18N
        TXTNome.setEnabled(false);

        TXTMarca.setText(bundle.getString("AlteraProduto.TXTMarca.text")); // NOI18N
        TXTMarca.setEnabled(false);

        TXTModelo.setText(bundle.getString("AlteraProduto.TXTModelo.text")); // NOI18N
        TXTModelo.setEnabled(false);

        javax.swing.GroupLayout PainelCamposdados1Layout = new javax.swing.GroupLayout(PainelCamposdados1);
        PainelCamposdados1.setLayout(PainelCamposdados1Layout);
        PainelCamposdados1Layout.setHorizontalGroup(
            PainelCamposdados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCamposdados1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCamposdados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TXTCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(TXTNome)
                    .addComponent(TXTMarca)
                    .addComponent(TXTModelo))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        PainelCamposdados1Layout.setVerticalGroup(
            PainelCamposdados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCamposdados1Layout.createSequentialGroup()
                .addComponent(TXTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        LValorCusto.setText(bundle.getString("AlteraProduto.LValorCusto.text")); // NOI18N

        LValorUnitario.setText(bundle.getString("AlteraProduto.LValorUnitario.text")); // NOI18N

        LQuantidade.setText(bundle.getString("AlteraProduto.LQuantidade.text")); // NOI18N

        TXTValorCusto.setText(bundle.getString("AlteraProduto.TXTValorCusto.text")); // NOI18N
        TXTValorCusto.setEnabled(false);

        TXTValorUnitario.setText(bundle.getString("AlteraProduto.TXTValorUnitario.text")); // NOI18N
        TXTValorUnitario.setEnabled(false);

        TXTQuantidade.setEnabled(false);

        javax.swing.GroupLayout PainelCamposdados2Layout = new javax.swing.GroupLayout(PainelCamposdados2);
        PainelCamposdados2.setLayout(PainelCamposdados2Layout);
        PainelCamposdados2Layout.setHorizontalGroup(
            PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCamposdados2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LValorCusto)
                    .addComponent(LValorUnitario)
                    .addComponent(LQuantidade))
                .addGap(40, 40, 40)
                .addGroup(PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXTQuantidade)
                    .addComponent(TXTValorUnitario)
                    .addComponent(TXTValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PainelCamposdados2Layout.setVerticalGroup(
            PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCamposdados2Layout.createSequentialGroup()
                .addGroup(PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LValorCusto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LValorUnitario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LQuantidade))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        LCodigo.setText(bundle.getString("AlteraProduto.LCodigo.text")); // NOI18N

        LNome.setText(bundle.getString("AlteraProduto.LNome.text")); // NOI18N

        LMarca.setText(bundle.getString("AlteraProduto.LMarca.text")); // NOI18N

        LModelo.setText(bundle.getString("AlteraProduto.LModelo.text")); // NOI18N

        LDescricao.setText(bundle.getString("AlteraProduto.LDescricao.text")); // NOI18N

        TXTDescricao.setColumns(20);
        TXTDescricao.setRows(5);
        TXTDescricao.setEnabled(false);
        PTXTDescricao.setViewportView(TXTDescricao);

        javax.swing.GroupLayout PainelCadastroProdutosLayout = new javax.swing.GroupLayout(PainelCadastroProdutos);
        PainelCadastroProdutos.setLayout(PainelCadastroProdutosLayout);
        PainelCadastroProdutosLayout.setHorizontalGroup(
            PainelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCadastroProdutosLayout.createSequentialGroup()
                        .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PainelCadastroProdutosLayout.createSequentialGroup()
                        .addGroup(PainelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PTXTDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelCadastroProdutosLayout.createSequentialGroup()
                                .addGroup(PainelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelCadastroProdutosLayout.createSequentialGroup()
                                        .addComponent(LDescricao)
                                        .addGap(227, 227, 227))
                                    .addGroup(PainelCadastroProdutosLayout.createSequentialGroup()
                                        .addGroup(PainelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LCodigo)
                                            .addComponent(LNome)
                                            .addComponent(LMarca)
                                            .addComponent(LModelo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PainelCamposdados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PainelCamposdados2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(14, 14, 14))))
        );
        PainelCadastroProdutosLayout.setVerticalGroup(
            PainelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastroProdutosLayout.createSequentialGroup()
                .addGroup(PainelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelCadastroProdutosLayout.createSequentialGroup()
                        .addComponent(LCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LDescricao))
                    .addComponent(PainelCamposdados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PainelCamposdados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PTXTDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PainelLocalizar.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("AlteraProduto.PainelLocalizar.border.title"))); // NOI18N

        TXTCodigoB.setText(bundle.getString("AlteraProduto.TXTCodigoB.text")); // NOI18N

        TXTNomeB.setText(bundle.getString("AlteraProduto.TXTNomeB.text")); // NOI18N

        TXTSobrenomeB.setText(bundle.getString("AlteraProduto.TXTSobrenomeB.text")); // NOI18N

        TXTModeloB.setText(bundle.getString("AlteraProduto.TXTModeloB.text")); // NOI18N

        TXTBusca.setText(bundle.getString("AlteraProduto.TXTBusca.text")); // NOI18N

        BotaoLocalizar.setText(bundle.getString("AlteraProduto.BotaoLocalizar.text")); // NOI18N

        javax.swing.GroupLayout PainelLocalizarLayout = new javax.swing.GroupLayout(PainelLocalizar);
        PainelLocalizar.setLayout(PainelLocalizarLayout);
        PainelLocalizarLayout.setHorizontalGroup(
            PainelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLocalizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TXTCodigoB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTNomeB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTSobrenomeB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTModeloB)
                .addGap(24, 24, 24)
                .addComponent(TXTBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoLocalizar)
                .addGap(32, 32, 32))
        );
        PainelLocalizarLayout.setVerticalGroup(
            PainelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLocalizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTCodigoB)
                        .addComponent(TXTNomeB)
                        .addComponent(TXTSobrenomeB)
                        .addComponent(BotaoLocalizar))
                    .addGroup(PainelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTModeloB)
                        .addComponent(TXTBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        TabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Marca", "Modelo", "Valor Unitario", "QTD"
            }
        ));
        TabelaResultado.setEnabled(false);
        SPTabela.setViewportView(TabelaResultado);
        if (TabelaResultado.getColumnModel().getColumnCount() > 0) {
            TabelaResultado.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("AlteraProduto.TabelaResultado.columnModel.title0")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("AlteraProduto.TabelaResultado.columnModel.title1")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("AlteraProduto.TabelaResultado.columnModel.title2")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("AlteraProduto.TabelaResultado.columnModel.title3")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("AlteraProduto.TabelaResultado.columnModel.title4")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("AlteraProduto.TabelaResultado.columnModel.title5")); // NOI18N
        }

        javax.swing.GroupLayout PainelTabelaLayout = new javax.swing.GroupLayout(PainelTabela);
        PainelTabela.setLayout(PainelTabelaLayout);
        PainelTabelaLayout.setHorizontalGroup(
            PainelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTabelaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(SPTabela)
                .addContainerGap())
        );
        PainelTabelaLayout.setVerticalGroup(
            PainelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTabelaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(SPTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelCadastroProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(PainelLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 667, Short.MAX_VALUE)
                    .addComponent(PainelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelCadastroProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoGravar;
    private javax.swing.JButton BotaoLocalizar;
    private javax.swing.JLabel LCodigo;
    private javax.swing.JLabel LDescricao;
    private javax.swing.JLabel LMarca;
    private javax.swing.JLabel LModelo;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LQuantidade;
    private javax.swing.JLabel LValorCusto;
    private javax.swing.JLabel LValorUnitario;
    private javax.swing.JScrollPane PTXTDescricao;
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel PainelCadastroProdutos;
    private javax.swing.JPanel PainelCamposdados1;
    private javax.swing.JPanel PainelCamposdados2;
    private javax.swing.JPanel PainelLocalizar;
    private javax.swing.JPanel PainelTabela;
    private javax.swing.JScrollPane SPTabela;
    private javax.swing.JTextField TXTBusca;
    private javax.swing.JTextField TXTCodigo;
    private javax.swing.JCheckBox TXTCodigoB;
    private javax.swing.JTextArea TXTDescricao;
    private javax.swing.JTextField TXTMarca;
    private javax.swing.JTextField TXTModelo;
    private javax.swing.JCheckBox TXTModeloB;
    private javax.swing.JTextField TXTNome;
    private javax.swing.JCheckBox TXTNomeB;
    private javax.swing.JSpinner TXTQuantidade;
    private javax.swing.JCheckBox TXTSobrenomeB;
    private javax.swing.JTextField TXTValorCusto;
    private javax.swing.JTextField TXTValorUnitario;
    private javax.swing.JTable TabelaResultado;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the PTXTDescricao
     */
    public javax.swing.JScrollPane getPTXTDescricao() {
        return PTXTDescricao;
    }

    /**
     * @param PTXTDescricao the PTXTDescricao to set
     */
    public void setPTXTDescricao(javax.swing.JScrollPane PTXTDescricao) {
        this.PTXTDescricao = PTXTDescricao;
    }

    /**
     * @return the TXTBusca
     */
    public javax.swing.JTextField getTXTBusca() {
        return TXTBusca;
    }

    /**
     * @param TXTBusca the TXTBusca to set
     */
    public void setTXTBusca(javax.swing.JTextField TXTBusca) {
        this.TXTBusca = TXTBusca;
    }

    /**
     * @return the TXTCodigo
     */
    public javax.swing.JTextField getTXTCodigo() {
        return TXTCodigo;
    }

    /**
     * @param TXTCodigo the TXTCodigo to set
     */
    public void setTXTCodigo(javax.swing.JTextField TXTCodigo) {
        this.TXTCodigo = TXTCodigo;
    }

    /**
     * @return the TXTCodigoB
     */
    public javax.swing.JCheckBox getTXTCodigoB() {
        return TXTCodigoB;
    }

    /**
     * @param TXTCodigoB the TXTCodigoB to set
     */
    public void setTXTCodigoB(javax.swing.JCheckBox TXTCodigoB) {
        this.TXTCodigoB = TXTCodigoB;
    }

    

    /**
     * @return the TXTDescricao
     */
    public javax.swing.JTextArea getTXTDescricao() {
        return TXTDescricao;
    }

    /**
     * @param TXTDescricao the TXTDescricao to set
     */
    public void setTXTDescricao(javax.swing.JTextArea TXTDescricao) {
        this.TXTDescricao = TXTDescricao;
    }

    /**
     * @return the TXTMarca
     */
    public javax.swing.JTextField getTXTMarca() {
        return TXTMarca;
    }

    /**
     * @param TXTMarca the TXTMarca to set
     */
    public void setTXTMarca(javax.swing.JTextField TXTMarca) {
        this.TXTMarca = TXTMarca;
    }

    /**
     * @return the TXTModelo
     */
    public javax.swing.JTextField getTXTModelo() {
        return TXTModelo;
    }

    /**
     * @param TXTModelo the TXTModelo to set
     */
    public void setTXTModelo(javax.swing.JTextField TXTModelo) {
        this.TXTModelo = TXTModelo;
    }

    /**
     * @return the TXTModeloB
     */
    public javax.swing.JCheckBox getTXTModeloB() {
        return TXTModeloB;
    }

    /**
     * @param TXTModeloB the TXTModeloB to set
     */
    public void setTXTModeloB(javax.swing.JCheckBox TXTModeloB) {
        this.TXTModeloB = TXTModeloB;
    }

    /**
     * @return the TXTNome
     */
    public javax.swing.JTextField getTXTNome() {
        return TXTNome;
    }

    /**
     * @param TXTNome the TXTNome to set
     */
    public void setTXTNome(javax.swing.JTextField TXTNome) {
        this.TXTNome = TXTNome;
    }

    /**
     * @return the TXTNomeB
     */
    public javax.swing.JCheckBox getTXTNomeB() {
        return TXTNomeB;
    }

    /**
     * @param TXTNomeB the TXTNomeB to set
     */
    public void setTXTNomeB(javax.swing.JCheckBox TXTNomeB) {
        this.TXTNomeB = TXTNomeB;
    }

    /**
     * @return the TXTQuantidade
     */
    public javax.swing.JSpinner getTXTQuantidade() {
        return TXTQuantidade;
    }

    /**
     * @param TXTQuantidade the TXTQuantidade to set
     */
    public void setTXTQuantidade(javax.swing.JSpinner TXTQuantidade) {
        this.TXTQuantidade = TXTQuantidade;
    }

    /**
     * @return the TXTSobrenomeB
     */
    public javax.swing.JCheckBox getTXTSobrenomeB() {
        return TXTSobrenomeB;
    }

    /**
     * @param TXTSobrenomeB the TXTSobrenomeB to set
     */
    public void setTXTSobrenomeB(javax.swing.JCheckBox TXTSobrenomeB) {
        this.TXTSobrenomeB = TXTSobrenomeB;
    }

    /**
     * @return the TXTValorCusto
     */
    public javax.swing.JTextField getTXTValorCusto() {
        return TXTValorCusto;
    }

    /**
     * @param TXTValorCusto the TXTValorCusto to set
     */
    public void setTXTValorCusto(javax.swing.JTextField TXTValorCusto) {
        this.TXTValorCusto = TXTValorCusto;
    }

    /**
     * @return the TXTValorUnitario
     */
    public javax.swing.JTextField getTXTValorUnitario() {
        return TXTValorUnitario;
    }

    /**
     * @param TXTValorUnitario the TXTValorUnitario to set
     */
    public void setTXTValorUnitario(javax.swing.JTextField TXTValorUnitario) {
        this.TXTValorUnitario = TXTValorUnitario;
    }

    /**
     * @return the TabelaResultado
     */
    public javax.swing.JTable getTabelaResultado() {
        return TabelaResultado;
    }

    /**
     * @param TabelaResultado the TabelaResultado to set
     */
    public void setTabelaResultado(javax.swing.JTable TabelaResultado) {
        this.TabelaResultado = TabelaResultado;
    }
}
