
package telas.jinternalframe;
import java.awt.event.ActionListener;
import listener.UsuarioListener;

public class CadastroUsuario extends javax.swing.JInternalFrame {
    private UsuarioListener listener = new UsuarioListener(this);
    /**
     * Creates new form LojaCadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCadastroUsuario = new javax.swing.JPanel();
        PainelDados = new javax.swing.JPanel();
        LUsuario = new javax.swing.JLabel();
        LSenha = new javax.swing.JLabel();
        LRSenha = new javax.swing.JLabel();
        TXTUsuario = new javax.swing.JTextField();
        TXTSenha = new javax.swing.JPasswordField();
        TXTRSenha = new javax.swing.JPasswordField();
        TXTEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LNome = new javax.swing.JLabel();
        LSobrenome = new javax.swing.JLabel();
        LCPF = new javax.swing.JLabel();
        LRG = new javax.swing.JLabel();
        TXTNome = new javax.swing.JTextField();
        TXTSobrenome = new javax.swing.JTextField();
        TXTCPF = new javax.swing.JTextField();
        TXTRG = new javax.swing.JTextField();
        PainelBotoes = new javax.swing.JPanel();
        BotaoCancelar = new javax.swing.JButton();
        BotaoGravar = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("telas/jinternalframe/Bundle"); // NOI18N
        PainelCadastroUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("CadastroUsuario.PainelCadastroUsuario.border.title"))); // NOI18N

        LUsuario.setText(bundle.getString("CadastroUsuario.LUsuario.text")); // NOI18N

        LSenha.setText(bundle.getString("CadastroUsuario.LSenha.text")); // NOI18N

        LRSenha.setText(bundle.getString("CadastroUsuario.LRSenha.text")); // NOI18N

        TXTUsuario.setText(bundle.getString("CadastroUsuario.TXTUsuario.text")); // NOI18N

        TXTSenha.setText(bundle.getString("CadastroUsuario.TXTSenha.text")); // NOI18N

        TXTRSenha.setText(bundle.getString("CadastroUsuario.TXTRSenha.text")); // NOI18N

        TXTEmail.setText(bundle.getString("CadastroUsuario.TXTEmail.text")); // NOI18N

        jLabel1.setText(bundle.getString("CadastroUsuario.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout PainelDadosLayout = new javax.swing.GroupLayout(PainelDados);
        PainelDados.setLayout(PainelDadosLayout);
        PainelDadosLayout.setHorizontalGroup(
            PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosLayout.createSequentialGroup()
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(79, 79, 79)
                        .addComponent(TXTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelDadosLayout.createSequentialGroup()
                                .addComponent(LUsuario)
                                .addGap(62, 62, 62))
                            .addGroup(PainelDadosLayout.createSequentialGroup()
                                .addComponent(LRSenha)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelDadosLayout.createSequentialGroup()
                                .addComponent(LSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXTUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(TXTSenha)
                            .addComponent(TXTRSenha))))
                .addGap(0, 47, Short.MAX_VALUE))
        );
        PainelDadosLayout.setVerticalGroup(
            PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosLayout.createSequentialGroup()
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addComponent(LUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(LSenha))
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addComponent(TXTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTRSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LRSenha))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        LNome.setText(bundle.getString("CadastroUsuario.LNome.text")); // NOI18N

        LSobrenome.setText(bundle.getString("CadastroUsuario.LSobrenome.text")); // NOI18N

        LCPF.setText(bundle.getString("CadastroUsuario.LCPF.text")); // NOI18N

        LRG.setText(bundle.getString("CadastroUsuario.LRG.text")); // NOI18N

        TXTNome.setText(bundle.getString("CadastroUsuario.TXTNome.text")); // NOI18N

        TXTSobrenome.setText(bundle.getString("CadastroUsuario.TXTSobrenome.text")); // NOI18N

        TXTCPF.setText(bundle.getString("CadastroUsuario.TXTCPF.text")); // NOI18N

        TXTRG.setText(bundle.getString("CadastroUsuario.TXTRG.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LRG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TXTRG, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TXTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LSobrenome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TXTSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LNome)
                        .addGap(86, 86, 86)
                        .addComponent(TXTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNome)
                    .addComponent(TXTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LSobrenome)
                    .addComponent(TXTSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LCPF)
                    .addComponent(TXTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LRG)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TXTRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout PainelCadastroUsuarioLayout = new javax.swing.GroupLayout(PainelCadastroUsuario);
        PainelCadastroUsuario.setLayout(PainelCadastroUsuarioLayout);
        PainelCadastroUsuarioLayout.setHorizontalGroup(
            PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        PainelCadastroUsuarioLayout.setVerticalGroup(
            PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroUsuarioLayout.createSequentialGroup()
                .addGroup(PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PainelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        BotaoCancelar.setText(bundle.getString("CadastroUsuario.BotaoCancelar.text")); // NOI18N
        BotaoCancelar.addActionListener(listener);
        BotaoCancelar.setActionCommand("cancelar");
        BotaoGravar.setText(bundle.getString("CadastroUsuario.BotaoGravar.text")); // NOI18N
        BotaoGravar.addActionListener(listener);
        BotaoGravar.setActionCommand("gravar");

        javax.swing.GroupLayout PainelBotoesLayout = new javax.swing.GroupLayout(PainelBotoes);
        PainelBotoes.setLayout(PainelBotoesLayout);
        PainelBotoesLayout.setHorizontalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(BotaoGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        PainelBotoesLayout.setVerticalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCancelar)
                    .addComponent(BotaoGravar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PainelCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoGravar;
    private javax.swing.JLabel LCPF;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LRG;
    private javax.swing.JLabel LRSenha;
    private javax.swing.JLabel LSenha;
    private javax.swing.JLabel LSobrenome;
    private javax.swing.JLabel LUsuario;
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel PainelCadastroUsuario;
    private javax.swing.JPanel PainelDados;
    private javax.swing.JTextField TXTCPF;
    private javax.swing.JTextField TXTEmail;
    private javax.swing.JTextField TXTNome;
    private javax.swing.JTextField TXTRG;
    private javax.swing.JPasswordField TXTRSenha;
    private javax.swing.JPasswordField TXTSenha;
    private javax.swing.JTextField TXTSobrenome;
    private javax.swing.JTextField TXTUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the TXTCPF
     */
    public javax.swing.JTextField getTXTCPF() {
        return TXTCPF;
    }

    /**
     * @param TXTCPF the TXTCPF to set
     */
    public void setTXTCPF(javax.swing.JTextField TXTCPF) {
        this.TXTCPF = TXTCPF;
    }

    /**
     * @return the TXTEmail
     */
    public javax.swing.JTextField getTXTEmail() {
        return TXTEmail;
    }

    /**
     * @param TXTEmail the TXTEmail to set
     */
    public void setTXTEmail(javax.swing.JTextField TXTEmail) {
        this.TXTEmail = TXTEmail;
    }

    /**
     * @return the TXTNome
     */
    public javax.swing.JTextField getTXTNome() {
        return TXTNome;
    }

    /**
     * @param TXTNome the TXTNome to set
     */
    public void setTXTNome(javax.swing.JTextField TXTNome) {
        this.TXTNome = TXTNome;
    }

    /**
     * @return the TXTRG
     */
    public javax.swing.JTextField getTXTRG() {
        return TXTRG;
    }

    /**
     * @param TXTRG the TXTRG to set
     */
    public void setTXTRG(javax.swing.JTextField TXTRG) {
        this.TXTRG = TXTRG;
    }

    /**
     * @return the TXTRSenha
     */
    public javax.swing.JPasswordField getTXTRSenha() {
        return TXTRSenha;
    }

    /**
     * @param TXTRSenha the TXTRSenha to set
     */
    public void setTXTRSenha(javax.swing.JPasswordField TXTRSenha) {
        this.TXTRSenha = TXTRSenha;
    }

    /**
     * @return the TXTSenha
     */
    public javax.swing.JPasswordField getTXTSenha() {
        return TXTSenha;
    }

    /**
     * @param TXTSenha the TXTSenha to set
     */
    public void setTXTSenha(javax.swing.JPasswordField TXTSenha) {
        this.TXTSenha = TXTSenha;
    }

    /**
     * @return the TXTSobrenome
     */
    public javax.swing.JTextField getTXTSobrenome() {
        return TXTSobrenome;
    }

    /**
     * @param TXTSobrenome the TXTSobrenome to set
     */
    public void setTXTSobrenome(javax.swing.JTextField TXTSobrenome) {
        this.TXTSobrenome = TXTSobrenome;
    }

    /**
     * @return the TXTUsuario
     */
    public javax.swing.JTextField getTXTUsuario() {
        return TXTUsuario;
    }

    /**
     * @param TXTUsuario the TXTUsuario to set
     */
    public void setTXTUsuario(javax.swing.JTextField TXTUsuario) {
        this.TXTUsuario = TXTUsuario;
    }

    
}
