
package telas.jinternalframe;
import listener.MovimentoCaixaListener;

public class MovimentoCaixa extends javax.swing.JInternalFrame {
    private MovimentoCaixaListener listener = new MovimentoCaixaListener(this);
    /**
     * Creates new form LojaContasReceber
     */
    public MovimentoCaixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelMovimentoCaixa = new javax.swing.JPanel();
        SPMovimento = new javax.swing.JScrollPane();
        TabelMovimentoCaixa = new javax.swing.JTable();
        LUltimasVendas = new javax.swing.JLabel();
        PainelBotoes = new javax.swing.JPanel();
        BotaoOK = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("telas/jinternalframe/Bundle"); // NOI18N
        PainelMovimentoCaixa.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("MovimentoCaixa.PainelMovimentoCaixa.border.title"))); // NOI18N

        TabelMovimentoCaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Sobrenome", "Data", "Hora", "Valor Total"
            }
        ));
        SPMovimento.setViewportView(TabelMovimentoCaixa);
        if (TabelMovimentoCaixa.getColumnModel().getColumnCount() > 0) {
            TabelMovimentoCaixa.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("MovimentoCaixa.TabelMovimentoCaixa.columnModel.title0")); // NOI18N
            TabelMovimentoCaixa.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("MovimentoCaixa.TabelMovimentoCaixa.columnModel.title1")); // NOI18N
            TabelMovimentoCaixa.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("MovimentoCaixa.TabelMovimentoCaixa.columnModel.title2")); // NOI18N
            TabelMovimentoCaixa.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("MovimentoCaixa.TabelMovimentoCaixa.columnModel.title3")); // NOI18N
            TabelMovimentoCaixa.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("MovimentoCaixa.TabelMovimentoCaixa.columnModel.title4")); // NOI18N
            TabelMovimentoCaixa.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("MovimentoCaixa.TabelMovimentoCaixa.columnModel.title5")); // NOI18N
        }

        LUltimasVendas.setText(bundle.getString("MovimentoCaixa.LUltimasVendas.text")); // NOI18N

        BotaoOK.setText(bundle.getString("MovimentoCaixa.BotaoOK.text")); // NOI18N
        BotaoOK.addActionListener(listener);
        BotaoOK.setActionCommand("ok");
        BotaoCancelar.setText(bundle.getString("MovimentoCaixa.BotaoCancelar.text")); // NOI18N
        BotaoCancelar.addActionListener(listener);
        BotaoCancelar.setActionCommand("cancelar");
        javax.swing.GroupLayout PainelBotoesLayout = new javax.swing.GroupLayout(PainelBotoes);
        PainelBotoes.setLayout(PainelBotoesLayout);
        PainelBotoesLayout.setHorizontalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(BotaoOK, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        PainelBotoesLayout.setVerticalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoOK)
                    .addComponent(BotaoCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout PainelMovimentoCaixaLayout = new javax.swing.GroupLayout(PainelMovimentoCaixa);
        PainelMovimentoCaixa.setLayout(PainelMovimentoCaixaLayout);
        PainelMovimentoCaixaLayout.setHorizontalGroup(
            PainelMovimentoCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMovimentoCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelMovimentoCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SPMovimento)
                    .addGroup(PainelMovimentoCaixaLayout.createSequentialGroup()
                        .addComponent(LUltimasVendas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMovimentoCaixaLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        PainelMovimentoCaixaLayout.setVerticalGroup(
            PainelMovimentoCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMovimentoCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LUltimasVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SPMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelMovimentoCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelMovimentoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoOK;
    private javax.swing.JLabel LUltimasVendas;
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel PainelMovimentoCaixa;
    private javax.swing.JScrollPane SPMovimento;
    private javax.swing.JTable TabelMovimentoCaixa;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the TabelMovimentoCaixa
     */
    public javax.swing.JTable getTabelMovimentoCaixa() {
        return TabelMovimentoCaixa;
    }

    /**
     * @param TabelMovimentoCaixa the TabelMovimentoCaixa to set
     */
    public void setTabelMovimentoCaixa(javax.swing.JTable TabelMovimentoCaixa) {
        this.TabelMovimentoCaixa = TabelMovimentoCaixa;
    }
}
