
package telas.jinternalframe;

import java.io.Serializable;
import listener.VendaListener;

public class Venda extends javax.swing.JInternalFrame implements Serializable{
    private static final long serialVersionUID = 1L;
    private VendaListener listener = new VendaListener(this);
    /**
     * Creates new form LojaVenda
     */
    public Venda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelVendaProdutos = new javax.swing.JPanel();
        PainelVenda = new javax.swing.JPanel();
        PainelItem = new javax.swing.JPanel();
        LCodigo = new javax.swing.JLabel();
        LNomeP = new javax.swing.JLabel();
        TXTNomeP = new javax.swing.JComboBox();
        TXTCodigoP = new javax.swing.JTextField();
        LPrecoVenda = new javax.swing.JLabel();
        TXTPrecoVenda = new javax.swing.JTextField();
        LMarca = new javax.swing.JLabel();
        TXTMarcas = new javax.swing.JComboBox();
        LQTD = new javax.swing.JLabel();
        TXTQTD = new javax.swing.JSpinner();
        LDesconto = new javax.swing.JLabel();
        TXTDesconto = new javax.swing.JTextField();
        BotaoIncluir = new javax.swing.JButton();
        PainelCarrinhoCompras = new javax.swing.JPanel();
        SPTabela = new javax.swing.JScrollPane();
        TabelaCarrinhoCompras = new javax.swing.JTable();
        PainelDadosVenda = new javax.swing.JPanel();
        LCODVenda = new javax.swing.JLabel();
        LCODCliente = new javax.swing.JLabel();
        LNome = new javax.swing.JLabel();
        LSobrenome = new javax.swing.JLabel();
        TXTCODVenda = new javax.swing.JTextField();
        TXTCODCliente = new javax.swing.JTextField();
        TXTNome = new javax.swing.JTextField();
        TXTSobrenome = new javax.swing.JTextField();
        LFormaPagamento = new javax.swing.JLabel();
        TXTFormaPagamento = new javax.swing.JComboBox();
        TXTNCheck = new javax.swing.JTextField();
        LValorTotal = new javax.swing.JLabel();
        TXTValorTotal = new javax.swing.JTextField();
        LNCheck = new javax.swing.JLabel();
        LNDOC = new javax.swing.JLabel();
        TXTNDOC = new javax.swing.JTextField();
        PainelBotoes = new javax.swing.JPanel();
        BotaoGravar = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("telas/jinternalframe/Bundle"); // NOI18N
        PainelVenda.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Venda.PainelVenda.border.title"))); // NOI18N

        PainelItem.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Venda.PainelItem.border.title"))); // NOI18N

        LCodigo.setText(bundle.getString("Venda.LCodigo.text")); // NOI18N

        LNomeP.setText(bundle.getString("Venda.LNomeP.text")); // NOI18N

        TXTNomeP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TXTCodigoP.setText(bundle.getString("Venda.TXTCodigoP.text")); // NOI18N

        LPrecoVenda.setText(bundle.getString("Venda.LPrecoVenda.text")); // NOI18N

        TXTPrecoVenda.setText(bundle.getString("Venda.TXTPrecoVenda.text")); // NOI18N

        LMarca.setText(bundle.getString("Venda.LMarca.text")); // NOI18N

        TXTMarcas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LQTD.setText(bundle.getString("Venda.LQTD.text")); // NOI18N

        LDesconto.setText(bundle.getString("Venda.LDesconto.text")); // NOI18N

        TXTDesconto.setText(bundle.getString("Venda.TXTDesconto.text")); // NOI18N

        BotaoIncluir.setText(bundle.getString("Venda.BotaoIncluir.text")); // NOI18N

        javax.swing.GroupLayout PainelItemLayout = new javax.swing.GroupLayout(PainelItem);
        PainelItem.setLayout(PainelItemLayout);
        PainelItemLayout.setHorizontalGroup(
            PainelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LCodigo)
                    .addComponent(LNomeP)
                    .addComponent(LPrecoVenda))
                .addGap(26, 26, 26)
                .addGroup(PainelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(PainelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LMarca)
                    .addComponent(LQTD)
                    .addComponent(LDesconto))
                .addGap(49, 49, 49)
                .addGroup(PainelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXTMarcas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXTDesconto)
                    .addComponent(TXTQTD))
                .addGap(18, 18, 18)
                .addComponent(BotaoIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 137, Short.MAX_VALUE))
        );
        PainelItemLayout.setVerticalGroup(
            PainelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCodigo)
                    .addComponent(TXTCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LMarca)
                    .addComponent(TXTMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoIncluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LNomeP)
                    .addGroup(PainelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LQTD)
                        .addComponent(TXTQTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LPrecoVenda)
                    .addComponent(TXTDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LDesconto)
                        .addComponent(TXTPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelCarrinhoCompras.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Venda.PainelCarrinhoCompras.border.title"))); // NOI18N

        TabelaCarrinhoCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Marca", "QTD", "Preco"
            }
        ));
        TabelaCarrinhoCompras.setEnabled(false);
        SPTabela.setViewportView(TabelaCarrinhoCompras);
        if (TabelaCarrinhoCompras.getColumnModel().getColumnCount() > 0) {
            TabelaCarrinhoCompras.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("Venda.TabelaCarrinhoCompras.columnModel.title0")); // NOI18N
            TabelaCarrinhoCompras.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("Venda.TabelaCarrinhoCompras.columnModel.title1")); // NOI18N
            TabelaCarrinhoCompras.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("Venda.TabelaCarrinhoCompras.columnModel.title2")); // NOI18N
            TabelaCarrinhoCompras.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("Venda.TabelaCarrinhoCompras.columnModel.title3")); // NOI18N
            TabelaCarrinhoCompras.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("Venda.TabelaCarrinhoCompras.columnModel.title4")); // NOI18N
        }

        javax.swing.GroupLayout PainelCarrinhoComprasLayout = new javax.swing.GroupLayout(PainelCarrinhoCompras);
        PainelCarrinhoCompras.setLayout(PainelCarrinhoComprasLayout);
        PainelCarrinhoComprasLayout.setHorizontalGroup(
            PainelCarrinhoComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCarrinhoComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SPTabela)
                .addContainerGap())
        );
        PainelCarrinhoComprasLayout.setVerticalGroup(
            PainelCarrinhoComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCarrinhoComprasLayout.createSequentialGroup()
                .addComponent(SPTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PainelDadosVenda.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Venda.PainelDadosVenda.border.title"))); // NOI18N

        LCODVenda.setText(bundle.getString("Venda.LCODVenda.text")); // NOI18N

        LCODCliente.setText(bundle.getString("Venda.LCODCliente.text")); // NOI18N

        LNome.setText(bundle.getString("Venda.LNome.text")); // NOI18N

        LSobrenome.setText(bundle.getString("Venda.LSobrenome.text")); // NOI18N

        TXTCODVenda.setEditable(false);
        TXTCODVenda.setText(bundle.getString("Venda.TXTCODVenda.text")); // NOI18N

        TXTCODCliente.setText(bundle.getString("Venda.TXTCODCliente.text")); // NOI18N

        TXTNome.setText(bundle.getString("Venda.TXTNome.text")); // NOI18N

        TXTSobrenome.setText(bundle.getString("Venda.TXTSobrenome.text")); // NOI18N

        LFormaPagamento.setText(bundle.getString("Venda.LFormaPagamento.text")); // NOI18N

        TXTFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dinheiro", "Cartao Credito", "Cartao Debito", "Check" }));

        TXTNCheck.setText(bundle.getString("Venda.TXTNCheck.text")); // NOI18N
        TXTNCheck.setEnabled(false);

        LValorTotal.setText(bundle.getString("Venda.LValorTotal.text")); // NOI18N

        TXTValorTotal.setText(bundle.getString("Venda.TXTValorTotal.text")); // NOI18N

        LNCheck.setText(bundle.getString("Venda.LNCheck.text")); // NOI18N

        LNDOC.setText(bundle.getString("Venda.LNDOC.text")); // NOI18N

        TXTNDOC.setText(bundle.getString("Venda.TXTNDOC.text")); // NOI18N
        TXTNDOC.setEnabled(false);

        javax.swing.GroupLayout PainelDadosVendaLayout = new javax.swing.GroupLayout(PainelDadosVenda);
        PainelDadosVenda.setLayout(PainelDadosVendaLayout);
        PainelDadosVendaLayout.setHorizontalGroup(
            PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LCODCliente)
                    .addComponent(LNome)
                    .addComponent(LSobrenome)
                    .addComponent(LCODVenda))
                .addGap(30, 30, 30)
                .addGroup(PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTCODVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TXTSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(TXTNome, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(TXTCODCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LFormaPagamento)
                    .addComponent(LNCheck)
                    .addComponent(LNDOC)
                    .addComponent(LValorTotal))
                .addGroup(PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDadosVendaLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(TXTValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TXTFormaPagamento, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TXTNCheck, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TXTNDOC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        PainelDadosVendaLayout.setVerticalGroup(
            PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelDadosVendaLayout.createSequentialGroup()
                        .addGroup(PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LFormaPagamento)
                            .addComponent(TXTFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LNCheck)
                            .addComponent(TXTNCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelDadosVendaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LNDOC))
                            .addGroup(PainelDadosVendaLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(TXTNDOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PainelDadosVendaLayout.createSequentialGroup()
                        .addGroup(PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LCODVenda)
                            .addComponent(TXTCODVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LCODCliente)
                            .addComponent(TXTCODCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LNome)
                            .addComponent(TXTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDadosVendaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LSobrenome)))
                    .addGroup(PainelDadosVendaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(TXTValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelDadosVendaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LValorTotal)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        BotaoGravar.setText(bundle.getString("Venda.BotaoGravar.text")); // NOI18N
        BotaoGravar.addActionListener(listener);
        BotaoGravar.setActionCommand("gravar");
        BotaoCancelar.setText(bundle.getString("Venda.BotaoCancelar.text")); // NOI18N
        BotaoCancelar.addActionListener(listener);
        BotaoCancelar.setActionCommand("gravar");
        javax.swing.GroupLayout PainelBotoesLayout = new javax.swing.GroupLayout(PainelBotoes);
        PainelBotoes.setLayout(PainelBotoesLayout);
        PainelBotoesLayout.setHorizontalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(BotaoGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelBotoesLayout.setVerticalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoGravar)
                    .addComponent(BotaoCancelar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelVendaLayout = new javax.swing.GroupLayout(PainelVenda);
        PainelVenda.setLayout(PainelVendaLayout);
        PainelVendaLayout.setHorizontalGroup(
            PainelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelDadosVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelCarrinhoCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PainelVendaLayout.setVerticalGroup(
            PainelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelCarrinhoCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelDadosVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelVendaProdutosLayout = new javax.swing.GroupLayout(PainelVendaProdutos);
        PainelVendaProdutos.setLayout(PainelVendaProdutosLayout);
        PainelVendaProdutosLayout.setHorizontalGroup(
            PainelVendaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVendaProdutosLayout.createSequentialGroup()
                .addComponent(PainelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PainelVendaProdutosLayout.setVerticalGroup(
            PainelVendaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVendaProdutosLayout.createSequentialGroup()
                .addComponent(PainelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelVendaProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelVendaProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoGravar;
    private javax.swing.JButton BotaoIncluir;
    private javax.swing.JLabel LCODCliente;
    private javax.swing.JLabel LCODVenda;
    private javax.swing.JLabel LCodigo;
    private javax.swing.JLabel LDesconto;
    private javax.swing.JLabel LFormaPagamento;
    private javax.swing.JLabel LMarca;
    private javax.swing.JLabel LNCheck;
    private javax.swing.JLabel LNDOC;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LNomeP;
    private javax.swing.JLabel LPrecoVenda;
    private javax.swing.JLabel LQTD;
    private javax.swing.JLabel LSobrenome;
    private javax.swing.JLabel LValorTotal;
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel PainelCarrinhoCompras;
    private javax.swing.JPanel PainelDadosVenda;
    private javax.swing.JPanel PainelItem;
    private javax.swing.JPanel PainelVenda;
    private javax.swing.JPanel PainelVendaProdutos;
    private javax.swing.JScrollPane SPTabela;
    private javax.swing.JTextField TXTCODCliente;
    private javax.swing.JTextField TXTCODVenda;
    private javax.swing.JTextField TXTCodigoP;
    private javax.swing.JTextField TXTDesconto;
    private javax.swing.JComboBox TXTFormaPagamento;
    private javax.swing.JComboBox TXTMarcas;
    private javax.swing.JTextField TXTNCheck;
    private javax.swing.JTextField TXTNDOC;
    private javax.swing.JTextField TXTNome;
    private javax.swing.JComboBox TXTNomeP;
    private javax.swing.JTextField TXTPrecoVenda;
    private javax.swing.JSpinner TXTQTD;
    private javax.swing.JTextField TXTSobrenome;
    private javax.swing.JTextField TXTValorTotal;
    private javax.swing.JTable TabelaCarrinhoCompras;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the TXTCODCliente
     */
    public javax.swing.JTextField getTXTCODCliente() {
        return TXTCODCliente;
    }

    /**
     * @param TXTCODCliente the TXTCODCliente to set
     */
    public void setTXTCODCliente(javax.swing.JTextField TXTCODCliente) {
        this.TXTCODCliente = TXTCODCliente;
    }

    /**
     * @return the TXTCODVenda
     */
    public javax.swing.JTextField getTXTCODVenda() {
        return TXTCODVenda;
    }

    /**
     * @param TXTCODVenda the TXTCODVenda to set
     */
    public void setTXTCODVenda(javax.swing.JTextField TXTCODVenda) {
        this.TXTCODVenda = TXTCODVenda;
    }

    /**
     * @return the TXTCodigoP
     */
    public javax.swing.JTextField getTXTCodigoP() {
        return TXTCodigoP;
    }

    /**
     * @param TXTCodigoP the TXTCodigoP to set
     */
    public void setTXTCodigoP(javax.swing.JTextField TXTCodigoP) {
        this.TXTCodigoP = TXTCodigoP;
    }

    
    /**
     * @return the TXTDesconto
     */
    public javax.swing.JTextField getTXTDesconto() {
        return TXTDesconto;
    }

    /**
     * @param TXTDesconto the TXTDesconto to set
     */
    public void setTXTDesconto(javax.swing.JTextField TXTDesconto) {
        this.TXTDesconto = TXTDesconto;
    }

    /**
     * @return the TXTFormaPagamento
     */
    public javax.swing.JComboBox getTXTFormaPagamento() {
        return TXTFormaPagamento;
    }

    /**
     * @param TXTFormaPagamento the TXTFormaPagamento to set
     */
    public void setTXTFormaPagamento(javax.swing.JComboBox TXTFormaPagamento) {
        this.TXTFormaPagamento = TXTFormaPagamento;
    }

    

    /**
     * @return the TXTMarcas
     */
    public javax.swing.JComboBox getTXTMarcas() {
        return TXTMarcas;
    }

    /**
     * @param TXTMarcas the TXTMarcas to set
     */
    public void setTXTMarcas(javax.swing.JComboBox TXTMarcas) {
        this.TXTMarcas = TXTMarcas;
    }

    /**
     * @return the TXTNCheck
     */
    public javax.swing.JTextField getTXTNCheck() {
        return TXTNCheck;
    }

    /**
     * @param TXTNCheck the TXTNCheck to set
     */
    public void setTXTNCheck(javax.swing.JTextField TXTNCheck) {
        this.TXTNCheck = TXTNCheck;
    }

    /**
     * @return the TXTNDOC
     */
    public javax.swing.JTextField getTXTNDOC() {
        return TXTNDOC;
    }

    /**
     * @param TXTNDOC the TXTNDOC to set
     */
    public void setTXTNDOC(javax.swing.JTextField TXTNDOC) {
        this.TXTNDOC = TXTNDOC;
    }

    /**
     * @return the TXTNome
     */
    public javax.swing.JTextField getTXTNome() {
        return TXTNome;
    }

    /**
     * @param TXTNome the TXTNome to set
     */
    public void setTXTNome(javax.swing.JTextField TXTNome) {
        this.TXTNome = TXTNome;
    }

    /**
     * @return the TXTNomeP
     */
    public javax.swing.JComboBox getTXTNomeP() {
        return TXTNomeP;
    }

    /**
     * @param TXTNomeP the TXTNomeP to set
     */
    public void setTXTNomeP(javax.swing.JComboBox TXTNomeP) {
        this.TXTNomeP = TXTNomeP;
    }

    /**
     * @return the TXTPrecoVenda
     */
    public javax.swing.JTextField getTXTPrecoVenda() {
        return TXTPrecoVenda;
    }

    /**
     * @param TXTPrecoVenda the TXTPrecoVenda to set
     */
    public void setTXTPrecoVenda(javax.swing.JTextField TXTPrecoVenda) {
        this.TXTPrecoVenda = TXTPrecoVenda;
    }

    /**
     * @return the TXTQTD
     */
    public javax.swing.JSpinner getTXTQTD() {
        return TXTQTD;
    }

    /**
     * @param TXTQTD the TXTQTD to set
     */
    public void setTXTQTD(javax.swing.JSpinner TXTQTD) {
        this.TXTQTD = TXTQTD;
    }

    /**
     * @return the TXTSobrenome
     */
    public javax.swing.JTextField getTXTSobrenome() {
        return TXTSobrenome;
    }

    /**
     * @param TXTSobrenome the TXTSobrenome to set
     */
    public void setTXTSobrenome(javax.swing.JTextField TXTSobrenome) {
        this.TXTSobrenome = TXTSobrenome;
    }

    /**
     * @return the TXTValorTotal
     */
    public javax.swing.JTextField getTXTValorTotal() {
        return TXTValorTotal;
    }

    /**
     * @param TXTValorTotal the TXTValorTotal to set
     */
    public void setTXTValorTotal(javax.swing.JTextField TXTValorTotal) {
        this.TXTValorTotal = TXTValorTotal;
    }

    /**
     * @return the TabelaCarrinhoCompras
     */
    public javax.swing.JTable getTabelaCarrinhoCompras() {
        return TabelaCarrinhoCompras;
    }

    /**
     * @param TabelaCarrinhoCompras the TabelaCarrinhoCompras to set
     */
    public void setTabelaCarrinhoCompras(javax.swing.JTable TabelaCarrinhoCompras) {
        this.TabelaCarrinhoCompras = TabelaCarrinhoCompras;
    }
}
