
package loja.telas.jinternalframe;


public class LojaRelatorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form LojaMovimentoCaixa
     */
    public LojaRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelRelatorioP = new javax.swing.JPanel();
        PainelRelatorio = new javax.swing.JPanel();
        TXTVendas = new javax.swing.JCheckBox();
        TXTContasReceber = new javax.swing.JCheckBox();
        TXTCliente = new javax.swing.JCheckBox();
        TXTDataI = new javax.swing.JTextField();
        LDataI = new javax.swing.JLabel();
        LDataF = new javax.swing.JLabel();
        TXTDataF = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        PainelBotoes = new javax.swing.JPanel();
        BotaoOK = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("loja/telas/jinternalframe/Bundle"); // NOI18N
        PainelRelatorioP.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("LojaRelatorio.PainelRelatorioP.border.title"))); // NOI18N

        TXTVendas.setText(bundle.getString("LojaRelatorio.TXTVendas.text")); // NOI18N

        TXTContasReceber.setText(bundle.getString("LojaRelatorio.TXTContasReceber.text")); // NOI18N

        TXTCliente.setText(bundle.getString("LojaRelatorio.TXTCliente.text")); // NOI18N

        TXTDataI.setText(bundle.getString("LojaRelatorio.TXTDataI.text")); // NOI18N
        TXTDataI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTDataIActionPerformed(evt);
            }
        });

        LDataI.setText(bundle.getString("LojaRelatorio.LDataI.text")); // NOI18N

        LDataF.setText(bundle.getString("LojaRelatorio.LDataF.text")); // NOI18N

        TXTDataF.setText(bundle.getString("LojaRelatorio.TXTDataF.text")); // NOI18N

        jCheckBox1.setText(bundle.getString("LojaRelatorio.jCheckBox1.text")); // NOI18N

        javax.swing.GroupLayout PainelRelatorioLayout = new javax.swing.GroupLayout(PainelRelatorio);
        PainelRelatorio.setLayout(PainelRelatorioLayout);
        PainelRelatorioLayout.setHorizontalGroup(
            PainelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRelatorioLayout.createSequentialGroup()
                .addComponent(TXTVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTContasReceber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LDataI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTDataI, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LDataF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTDataF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        PainelRelatorioLayout.setVerticalGroup(
            PainelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTVendas)
                    .addComponent(TXTContasReceber)
                    .addComponent(TXTCliente)
                    .addComponent(TXTDataI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LDataI)
                    .addComponent(LDataF)
                    .addComponent(TXTDataF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BotaoOK.setText(bundle.getString("LojaRelatorio.BotaoOK.text")); // NOI18N

        BotaoCancelar.setText(bundle.getString("LojaRelatorio.BotaoCancelar.text")); // NOI18N

        javax.swing.GroupLayout PainelBotoesLayout = new javax.swing.GroupLayout(PainelBotoes);
        PainelBotoes.setLayout(PainelBotoesLayout);
        PainelBotoesLayout.setHorizontalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BotaoOK, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        PainelBotoesLayout.setVerticalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelBotoesLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoOK)
                    .addComponent(BotaoCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout PainelRelatorioPLayout = new javax.swing.GroupLayout(PainelRelatorioP);
        PainelRelatorioP.setLayout(PainelRelatorioPLayout);
        PainelRelatorioPLayout.setHorizontalGroup(
            PainelRelatorioPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRelatorioPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelRelatorioPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        PainelRelatorioPLayout.setVerticalGroup(
            PainelRelatorioPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRelatorioPLayout.createSequentialGroup()
                .addComponent(PainelRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelRelatorioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelRelatorioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTDataIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTDataIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTDataIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoOK;
    private javax.swing.JLabel LDataF;
    private javax.swing.JLabel LDataI;
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel PainelRelatorio;
    private javax.swing.JPanel PainelRelatorioP;
    private javax.swing.JCheckBox TXTCliente;
    private javax.swing.JCheckBox TXTContasReceber;
    private javax.swing.JTextField TXTDataF;
    private javax.swing.JTextField TXTDataI;
    private javax.swing.JCheckBox TXTVendas;
    private javax.swing.JCheckBox jCheckBox1;
    // End of variables declaration//GEN-END:variables
}
