
package loja.telas.jinternalframe;
import loja.botoes.LojaBotoes;

public class LojaConsultaVendas extends javax.swing.JInternalFrame {

    /**
     * Creates new form LojaConsultaVendas
     */
    public LojaConsultaVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelConsultaVendas = new javax.swing.JPanel();
        PainelBotoes = new javax.swing.JPanel();
        BotaoOK = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();
        SPTabela = new javax.swing.JScrollPane();
        TabelaResultado = new javax.swing.JTable();
        TXTCodigo = new javax.swing.JCheckBox();
        TXTNome = new javax.swing.JCheckBox();
        TXTSobrenome = new javax.swing.JCheckBox();
        TXTData = new javax.swing.JCheckBox();
        TXTConsuta = new javax.swing.JTextField();
        BotaoConsultar = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("loja/telas/jinternalframe/Bundle"); // NOI18N
        PainelConsultaVendas.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("LojaConsultaVendas.PainelConsultaVendas.border.title"))); // NOI18N

        BotaoOK.setText(bundle.getString("LojaConsultaVendas.BotaoOK.text")); // NOI18N
        BotaoOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoOKActionPerformed(evt);
            }
        });

        BotaoCancelar.setText(bundle.getString("LojaConsultaVendas.BotaoCancelar.text")); // NOI18N
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelBotoesLayout = new javax.swing.GroupLayout(PainelBotoes);
        PainelBotoes.setLayout(PainelBotoesLayout);
        PainelBotoesLayout.setHorizontalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(BotaoOK, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        PainelBotoesLayout.setVerticalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelBotoesLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoOK)
                    .addComponent(BotaoCancelar))
                .addContainerGap())
        );

        TabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Sobrenome", "CPF", "RG", "Data ", "Hora ", "Valor Total"
            }
        ));
        SPTabela.setViewportView(TabelaResultado);
        if (TabelaResultado.getColumnModel().getColumnCount() > 0) {
            TabelaResultado.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("LojaConsultaVendas.TabelaResultado.columnModel.title0")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("LojaConsultaVendas.TabelaResultado.columnModel.title1")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("LojaConsultaVendas.TabelaResultado.columnModel.title2")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("LojaConsultaVendas.TabelaResultado.columnModel.title3")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("LojaConsultaVendas.TabelaResultado.columnModel.title4")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("LojaConsultaVendas.TabelaResultado.columnModel.title5")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(6).setHeaderValue(bundle.getString("LojaConsultaVendas.TabelaResultado.columnModel.title6")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(7).setHeaderValue(bundle.getString("LojaConsultaVendas.TabelaResultado.columnModel.title7")); // NOI18N
        }

        TXTCodigo.setText(bundle.getString("LojaConsultaVendas.TXTCodigo.text")); // NOI18N

        TXTNome.setText(bundle.getString("LojaConsultaVendas.TXTNome.text")); // NOI18N

        TXTSobrenome.setText(bundle.getString("LojaConsultaVendas.TXTSobrenome.text")); // NOI18N

        TXTData.setText(bundle.getString("LojaConsultaVendas.TXTData.text")); // NOI18N

        TXTConsuta.setText(bundle.getString("LojaConsultaVendas.TXTConsuta.text")); // NOI18N

        BotaoConsultar.setText(bundle.getString("LojaConsultaVendas.BotaoConsultar.text")); // NOI18N
        BotaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelConsultaVendasLayout = new javax.swing.GroupLayout(PainelConsultaVendas);
        PainelConsultaVendas.setLayout(PainelConsultaVendasLayout);
        PainelConsultaVendasLayout.setHorizontalGroup(
            PainelConsultaVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelConsultaVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelConsultaVendasLayout.createSequentialGroup()
                        .addComponent(TXTCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(TXTNome)
                        .addGap(18, 18, 18)
                        .addComponent(TXTSobrenome)
                        .addGap(18, 18, 18)
                        .addComponent(TXTData)
                        .addGap(18, 18, 18)
                        .addComponent(TXTConsuta, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(BotaoConsultar))
                    .addComponent(SPTabela))
                .addContainerGap())
            .addGroup(PainelConsultaVendasLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelConsultaVendasLayout.setVerticalGroup(
            PainelConsultaVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelConsultaVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelConsultaVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTCodigo)
                    .addComponent(TXTNome)
                    .addComponent(TXTSobrenome)
                    .addComponent(TXTData)
                    .addComponent(TXTConsuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SPTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelConsultaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PainelConsultaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoOKActionPerformed
        // TODO add your handling code here:
        LojaBotoes LB = new LojaBotoes();
        LB.OK();
    }//GEN-LAST:event_BotaoOKActionPerformed

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        // TODO add your handling code here:
        LojaBotoes LB = new LojaBotoes();
        LB.Cancelar();
    }//GEN-LAST:event_BotaoCancelarActionPerformed

    private void BotaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultarActionPerformed
        // TODO add your handling code here:
        LojaBotoes LB = new LojaBotoes();
        LB.Consultar();
    }//GEN-LAST:event_BotaoConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoConsultar;
    private javax.swing.JButton BotaoOK;
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel PainelConsultaVendas;
    private javax.swing.JScrollPane SPTabela;
    private javax.swing.JCheckBox TXTCodigo;
    private javax.swing.JTextField TXTConsuta;
    private javax.swing.JCheckBox TXTData;
    private javax.swing.JCheckBox TXTNome;
    private javax.swing.JCheckBox TXTSobrenome;
    private javax.swing.JTable TabelaResultado;
    // End of variables declaration//GEN-END:variables
}
