
package loja.telas.jinternalframe;
import loja.botoes.LojaBotoes;

public class LojaAlteraCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form LojaCadastroCliente
     */
    public LojaAlteraCliente() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCADCliente = new javax.swing.JPanel();
        PainelInfCADCliente = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LCodigo = new javax.swing.JLabel();
        TXTCodigo = new javax.swing.JTextField();
        LNome = new javax.swing.JLabel();
        TXTNome = new javax.swing.JTextField();
        LSobrenome = new javax.swing.JLabel();
        TXTSobrenome = new javax.swing.JTextField();
        LSexo = new javax.swing.JLabel();
        TXTSexo = new javax.swing.JComboBox();
        LCPF = new javax.swing.JLabel();
        TXTCPF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        LDatanascimento = new javax.swing.JLabel();
        TXTDataNascimento = new javax.swing.JTextField();
        LDatacadastro = new javax.swing.JLabel();
        TXTDataCadastro = new javax.swing.JTextField();
        LEstadocivil = new javax.swing.JLabel();
        TXTRG = new javax.swing.JTextField();
        LRG = new javax.swing.JLabel();
        TXTEstadoCivil = new javax.swing.JComboBox();
        PainelEndCADCliente = new javax.swing.JPanel();
        TXTtelefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TXTEmail = new javax.swing.JTextField();
        TXTEndereco = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TXTLogadouro = new javax.swing.JTextField();
        TXTCidade = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TXTComplemento = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TXTPais = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TXTReferencia = new javax.swing.JTextField();
        TXTUF = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TXTCEP = new javax.swing.JTextField();
        TXTNumero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TXTBairro = new javax.swing.JTextField();
        TXTCelular = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PainelBotoesCADCliente = new javax.swing.JPanel();
        JBGravar = new javax.swing.JButton();
        JBExcluir = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        PainelLocalizar = new javax.swing.JPanel();
        TXTCodigoB = new javax.swing.JCheckBox();
        TXTNomeB = new javax.swing.JCheckBox();
        TXTSobrenomeB = new javax.swing.JCheckBox();
        TXTBusca = new javax.swing.JTextField();
        BotaoLocalizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaResultado = new javax.swing.JTable();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("loja/telas/jinternalframe/Bundle"); // NOI18N
        PainelCADCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("LojaAlteraCliente.PainelCADCliente.border.title"))); // NOI18N

        PainelInfCADCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("LojaAlteraCliente.PainelInfCADCliente.border.title"))); // NOI18N

        LCodigo.setText(bundle.getString("LojaAlteraCliente.LCodigo.text")); // NOI18N

        TXTCodigo.setEditable(false);
        TXTCodigo.setText(bundle.getString("LojaAlteraCliente.TXTCodigo.text")); // NOI18N

        LNome.setText(bundle.getString("LojaAlteraCliente.LNome.text")); // NOI18N

        TXTNome.setEditable(false);
        TXTNome.setText(bundle.getString("LojaAlteraCliente.TXTNome.text")); // NOI18N

        LSobrenome.setText(bundle.getString("LojaAlteraCliente.LSobrenome.text")); // NOI18N

        TXTSobrenome.setEditable(false);
        TXTSobrenome.setText(bundle.getString("LojaAlteraCliente.TXTSobrenome.text")); // NOI18N

        LSexo.setText(bundle.getString("LojaAlteraCliente.LSexo.text")); // NOI18N

        TXTSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        TXTSexo.setEnabled(false);

        LCPF.setText(bundle.getString("LojaAlteraCliente.LCPF.text")); // NOI18N

        TXTCPF.setEditable(false);
        TXTCPF.setText(bundle.getString("LojaAlteraCliente.TXTCPF.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LCodigo)
                    .addComponent(LNome)
                    .addComponent(LSobrenome)
                    .addComponent(LSexo)
                    .addComponent(LCPF))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TXTCodigo)
                        .addComponent(TXTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TXTCPF)
                        .addComponent(TXTSobrenome)
                        .addComponent(TXTSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCodigo)
                    .addComponent(TXTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LSobrenome)
                    .addComponent(TXTSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LSexo)
                    .addComponent(TXTSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LCPF)
                    .addComponent(TXTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LDatanascimento.setText(bundle.getString("LojaAlteraCliente.LDatanascimento.text")); // NOI18N

        TXTDataNascimento.setEditable(false);
        TXTDataNascimento.setText(bundle.getString("LojaAlteraCliente.TXTDataNascimento.text")); // NOI18N

        LDatacadastro.setText(bundle.getString("LojaAlteraCliente.LDatacadastro.text")); // NOI18N

        TXTDataCadastro.setEditable(false);
        TXTDataCadastro.setText(bundle.getString("LojaAlteraCliente.TXTDataCadastro.text")); // NOI18N

        LEstadocivil.setText(bundle.getString("LojaAlteraCliente.LEstadocivil.text")); // NOI18N

        TXTRG.setEditable(false);
        TXTRG.setText(bundle.getString("LojaAlteraCliente.TXTRG.text")); // NOI18N

        LRG.setText(bundle.getString("LojaAlteraCliente.LRG.text")); // NOI18N

        TXTEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viuvo(a)" }));
        TXTEstadoCivil.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LDatanascimento)
                    .addComponent(LDatacadastro)
                    .addComponent(LEstadocivil)
                    .addComponent(LRG))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXTRG)
                    .addComponent(TXTDataNascimento)
                    .addComponent(TXTDataCadastro)
                    .addComponent(TXTEstadoCivil, 0, 150, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LDatanascimento)
                    .addComponent(TXTDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LDatacadastro)
                    .addComponent(TXTDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LEstadocivil)
                    .addComponent(TXTEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LRG)
                    .addComponent(TXTRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelInfCADClienteLayout = new javax.swing.GroupLayout(PainelInfCADCliente);
        PainelInfCADCliente.setLayout(PainelInfCADClienteLayout);
        PainelInfCADClienteLayout.setHorizontalGroup(
            PainelInfCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInfCADClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        PainelInfCADClienteLayout.setVerticalGroup(
            PainelInfCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInfCADClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelInfCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        PainelEndCADCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("LojaAlteraCliente.PainelEndCADCliente.border.title"))); // NOI18N

        TXTtelefone.setEditable(false);

        jLabel8.setText(bundle.getString("LojaAlteraCliente.jLabel8.text")); // NOI18N

        jLabel10.setText(bundle.getString("LojaAlteraCliente.jLabel10.text")); // NOI18N

        TXTEmail.setEditable(false);

        TXTEndereco.setEditable(false);

        jLabel11.setText(bundle.getString("LojaAlteraCliente.jLabel11.text")); // NOI18N

        jLabel18.setText(bundle.getString("LojaAlteraCliente.jLabel18.text")); // NOI18N

        TXTLogadouro.setEditable(false);

        TXTCidade.setEditable(false);

        jLabel14.setText(bundle.getString("LojaAlteraCliente.jLabel14.text")); // NOI18N

        jLabel19.setText(bundle.getString("LojaAlteraCliente.jLabel19.text")); // NOI18N

        TXTComplemento.setEditable(false);

        jLabel16.setText(bundle.getString("LojaAlteraCliente.jLabel16.text")); // NOI18N

        TXTPais.setEditable(false);

        jLabel20.setText(bundle.getString("LojaAlteraCliente.jLabel20.text")); // NOI18N

        TXTReferencia.setEditable(false);

        TXTUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acre (AC)", "Alagoas (AL)", "Amapá (AP)", "Amazonas (AM)", "Bahia (BA)", "Ceará (CE)", "Distrito Federal (DF)", "Espírito Santo (ES)", "Goiás (GO)", "Maranhão (MA)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", "Pará (PA)", "Paraíba (PB)", "Paraná (PR)", "Pernanbuco (PE)", "Piauí (PI)", "Rio Grande do Norte (RN)", "Rio Grande do Sul (RS)", "Rondônia (RO)", "Roraima (RR)", "Santa Catarina (SC)", "São Paulo (SP)", "Sergipe (SE)", "Tocantins(TO)" }));
        TXTUF.setEnabled(false);

        jLabel15.setText(bundle.getString("LojaAlteraCliente.jLabel15.text")); // NOI18N

        jLabel17.setText(bundle.getString("LojaAlteraCliente.jLabel17.text")); // NOI18N

        TXTCEP.setEditable(false);

        TXTNumero.setEditable(false);

        jLabel13.setText(bundle.getString("LojaAlteraCliente.jLabel13.text")); // NOI18N

        jLabel12.setText(bundle.getString("LojaAlteraCliente.jLabel12.text")); // NOI18N

        TXTBairro.setEditable(false);

        TXTCelular.setEditable(false);

        jLabel9.setText(bundle.getString("LojaAlteraCliente.jLabel9.text")); // NOI18N

        javax.swing.GroupLayout PainelEndCADClienteLayout = new javax.swing.GroupLayout(PainelEndCADCliente);
        PainelEndCADCliente.setLayout(PainelEndCADClienteLayout);
        PainelEndCADClienteLayout.setHorizontalGroup(
            PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEndCADClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelEndCADClienteLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PainelEndCADClienteLayout.createSequentialGroup()
                        .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PainelEndCADClienteLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXTComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelEndCADClienteLayout.createSequentialGroup()
                                .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTtelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelEndCADClienteLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXTPais, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelEndCADClienteLayout.createSequentialGroup()
                                .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel18))
                                .addGap(60, 60, 60)
                                .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TXTCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(TXTLogadouro, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                    .addComponent(TXTEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addComponent(jLabel20))))
                .addGap(27, 27, 27)
                .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXTBairro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TXTCEP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TXTUF, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXTReferencia)
                    .addComponent(TXTCelular)
                    .addComponent(TXTNumero))
                .addGap(55, 55, 55))
        );
        PainelEndCADClienteLayout.setVerticalGroup(
            PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEndCADClienteLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelEndCADClienteLayout.createSequentialGroup()
                        .addComponent(TXTCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(TXTBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TXTReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelEndCADClienteLayout.createSequentialGroup()
                        .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(TXTtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TXTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addComponent(TXTEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel13)
                            .addComponent(TXTLogadouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(TXTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(TXTComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelEndCADClienteLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelEndCADClienteLayout.createSequentialGroup()
                                .addGroup(PainelEndCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(TXTPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );

        JBGravar.setText(bundle.getString("LojaAlteraCliente.JBGravar.text")); // NOI18N
        JBGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGravarActionPerformed(evt);
            }
        });

        JBExcluir.setText(bundle.getString("LojaAlteraCliente.JBExcluir.text")); // NOI18N
        JBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBExcluirActionPerformed(evt);
            }
        });

        JBCancelar.setText(bundle.getString("LojaAlteraCliente.JBCancelar.text")); // NOI18N
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelBotoesCADClienteLayout = new javax.swing.GroupLayout(PainelBotoesCADCliente);
        PainelBotoesCADCliente.setLayout(PainelBotoesCADClienteLayout);
        PainelBotoesCADClienteLayout.setHorizontalGroup(
            PainelBotoesCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesCADClienteLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(JBGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(JBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(JBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelBotoesCADClienteLayout.setVerticalGroup(
            PainelBotoesCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelBotoesCADClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelBotoesCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBGravar)
                    .addComponent(JBExcluir)
                    .addComponent(JBCancelar))
                .addContainerGap())
        );

        PainelLocalizar.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("LojaAlteraCliente.PainelLocalizar.border.title"))); // NOI18N

        TXTCodigoB.setText(bundle.getString("LojaAlteraCliente.TXTCodigoB.text")); // NOI18N

        TXTNomeB.setText(bundle.getString("LojaAlteraCliente.TXTNomeB.text")); // NOI18N

        TXTSobrenomeB.setText(bundle.getString("LojaAlteraCliente.TXTSobrenomeB.text")); // NOI18N

        TXTBusca.setText(bundle.getString("LojaAlteraCliente.TXTBusca.text")); // NOI18N

        BotaoLocalizar.setText(bundle.getString("LojaAlteraCliente.BotaoLocalizar.text")); // NOI18N
        BotaoLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLocalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelLocalizarLayout = new javax.swing.GroupLayout(PainelLocalizar);
        PainelLocalizar.setLayout(PainelLocalizarLayout);
        PainelLocalizarLayout.setHorizontalGroup(
            PainelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLocalizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TXTCodigoB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTNomeB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTSobrenomeB)
                .addGap(18, 18, 18)
                .addComponent(TXTBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoLocalizar)
                .addGap(32, 32, 32))
        );
        PainelLocalizarLayout.setVerticalGroup(
            PainelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLocalizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTCodigoB)
                    .addComponent(TXTNomeB)
                    .addComponent(TXTSobrenomeB)
                    .addComponent(TXTBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoLocalizar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        TabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Sobrenome", "CPF", "RG"
            }
        ));
        jScrollPane2.setViewportView(TabelaResultado);
        if (TabelaResultado.getColumnModel().getColumnCount() > 0) {
            TabelaResultado.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("LojaAlteraCliente.TabelaResultado.columnModel.title0")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("LojaAlteraCliente.TabelaResultado.columnModel.title1")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("LojaAlteraCliente.TabelaResultado.columnModel.title2")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("LojaAlteraCliente.TabelaResultado.columnModel.title3")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("LojaAlteraCliente.TabelaResultado.columnModel.title4")); // NOI18N
        }

        javax.swing.GroupLayout PainelCADClienteLayout = new javax.swing.GroupLayout(PainelCADCliente);
        PainelCADCliente.setLayout(PainelCADClienteLayout);
        PainelCADClienteLayout.setHorizontalGroup(
            PainelCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCADClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PainelBotoesCADCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PainelInfCADCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelEndCADCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelLocalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelCADClienteLayout.setVerticalGroup(
            PainelCADClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCADClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelInfCADCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelEndCADCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelBotoesCADCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelCADCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelCADCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLocalizarActionPerformed
        // TODO add your handling code here:
        LojaBotoes LB = new LojaBotoes();
        LB.Localizar();
    }//GEN-LAST:event_BotaoLocalizarActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        // TODO add your handling code here:
        LojaBotoes LB = new LojaBotoes();
        LB.Cancelar();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBExcluirActionPerformed
        // TODO add your handling code here:
        LojaBotoes LB = new LojaBotoes();
        LB.Excluir();
    }//GEN-LAST:event_JBExcluirActionPerformed

    private void JBGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGravarActionPerformed
        // TODO add your handling code here:
        LojaBotoes LB = new LojaBotoes();
        LB.Gravar();
    }//GEN-LAST:event_JBGravarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoLocalizar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBExcluir;
    private javax.swing.JButton JBGravar;
    private javax.swing.JLabel LCPF;
    private javax.swing.JLabel LCodigo;
    private javax.swing.JLabel LDatacadastro;
    private javax.swing.JLabel LDatanascimento;
    private javax.swing.JLabel LEstadocivil;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LRG;
    private javax.swing.JLabel LSexo;
    private javax.swing.JLabel LSobrenome;
    private javax.swing.JPanel PainelBotoesCADCliente;
    private javax.swing.JPanel PainelCADCliente;
    private javax.swing.JPanel PainelEndCADCliente;
    private javax.swing.JPanel PainelInfCADCliente;
    private javax.swing.JPanel PainelLocalizar;
    private javax.swing.JTextField TXTBairro;
    private javax.swing.JTextField TXTBusca;
    private javax.swing.JTextField TXTCEP;
    private javax.swing.JTextField TXTCPF;
    private javax.swing.JTextField TXTCelular;
    private javax.swing.JTextField TXTCidade;
    private javax.swing.JTextField TXTCodigo;
    private javax.swing.JCheckBox TXTCodigoB;
    private javax.swing.JTextField TXTComplemento;
    private javax.swing.JTextField TXTDataCadastro;
    private javax.swing.JTextField TXTDataNascimento;
    private javax.swing.JTextField TXTEmail;
    private javax.swing.JTextField TXTEndereco;
    private javax.swing.JComboBox TXTEstadoCivil;
    private javax.swing.JTextField TXTLogadouro;
    private javax.swing.JTextField TXTNome;
    private javax.swing.JCheckBox TXTNomeB;
    private javax.swing.JTextField TXTNumero;
    private javax.swing.JTextField TXTPais;
    private javax.swing.JTextField TXTRG;
    private javax.swing.JTextField TXTReferencia;
    private javax.swing.JComboBox TXTSexo;
    private javax.swing.JTextField TXTSobrenome;
    private javax.swing.JCheckBox TXTSobrenomeB;
    private javax.swing.JComboBox TXTUF;
    private javax.swing.JTextField TXTtelefone;
    private javax.swing.JTable TabelaResultado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
