
package loja.telas.jinternalframe;


public class LojaAlteraUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form LojaCadastroUsuario
     */
    public LojaAlteraUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCadastroUsuario = new javax.swing.JPanel();
        PainelDados = new javax.swing.JPanel();
        LNome = new javax.swing.JLabel();
        LSenha = new javax.swing.JLabel();
        LRSenha = new javax.swing.JLabel();
        TXTUsuario = new javax.swing.JTextField();
        TXTSenha = new javax.swing.JPasswordField();
        TXTRSenha = new javax.swing.JPasswordField();
        PainelBotoes = new javax.swing.JPanel();
        BotaoGravar = new javax.swing.JButton();
        BotaoExcluir = new javax.swing.JButton();
        PainelLocalizarUsuario = new javax.swing.JPanel();
        LUsuario = new javax.swing.JLabel();
        LSenhaAtual = new javax.swing.JLabel();
        TXTUsuarioBusca = new javax.swing.JTextField();
        TXTSenhaAtual = new javax.swing.JPasswordField();
        BotaoLocalizar = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("loja/telas/jinternalframe/Bundle"); // NOI18N
        PainelCadastroUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("LojaAlteraUsuario.PainelCadastroUsuario.border.title"))); // NOI18N

        LNome.setText(bundle.getString("LojaAlteraUsuario.LNome.text")); // NOI18N

        LSenha.setText(bundle.getString("LojaAlteraUsuario.LSenha.text")); // NOI18N

        LRSenha.setText(bundle.getString("LojaAlteraUsuario.LRSenha.text")); // NOI18N

        TXTUsuario.setText(bundle.getString("LojaAlteraUsuario.TXTUsuario.text")); // NOI18N
        TXTUsuario.setEnabled(false);

        TXTSenha.setText(bundle.getString("LojaAlteraUsuario.TXTSenha.text")); // NOI18N
        TXTSenha.setEnabled(false);

        TXTRSenha.setText(bundle.getString("LojaAlteraUsuario.TXTRSenha.text")); // NOI18N
        TXTRSenha.setEnabled(false);

        javax.swing.GroupLayout PainelDadosLayout = new javax.swing.GroupLayout(PainelDados);
        PainelDados.setLayout(PainelDadosLayout);
        PainelDadosLayout.setHorizontalGroup(
            PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosLayout.createSequentialGroup()
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LNome)
                    .addComponent(LSenha)
                    .addComponent(LRSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXTUsuario)
                    .addComponent(TXTSenha)
                    .addComponent(TXTRSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        PainelDadosLayout.setVerticalGroup(
            PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosLayout.createSequentialGroup()
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addComponent(LNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LRSenha))
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addComponent(TXTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTRSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelCadastroUsuarioLayout = new javax.swing.GroupLayout(PainelCadastroUsuario);
        PainelCadastroUsuario.setLayout(PainelCadastroUsuarioLayout);
        PainelCadastroUsuarioLayout.setHorizontalGroup(
            PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelCadastroUsuarioLayout.setVerticalGroup(
            PainelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BotaoGravar.setText(bundle.getString("LojaAlteraUsuario.BotaoGravar.text")); // NOI18N

        BotaoExcluir.setText(bundle.getString("LojaAlteraUsuario.BotaoExcluir.text")); // NOI18N

        javax.swing.GroupLayout PainelBotoesLayout = new javax.swing.GroupLayout(PainelBotoes);
        PainelBotoes.setLayout(PainelBotoesLayout);
        PainelBotoesLayout.setHorizontalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(BotaoGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(BotaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        PainelBotoesLayout.setVerticalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoGravar)
                    .addComponent(BotaoExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelLocalizarUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("LojaAlteraUsuario.PainelLocalizarUsuario.border.title"))); // NOI18N

        LUsuario.setText(bundle.getString("LojaAlteraUsuario.LUsuario.text")); // NOI18N

        LSenhaAtual.setText(bundle.getString("LojaAlteraUsuario.LSenhaAtual.text")); // NOI18N

        TXTUsuarioBusca.setText(bundle.getString("LojaAlteraUsuario.TXTUsuarioBusca.text")); // NOI18N

        TXTSenhaAtual.setText(bundle.getString("LojaAlteraUsuario.TXTSenhaAtual.text")); // NOI18N
        TXTSenhaAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTSenhaAtualActionPerformed(evt);
            }
        });

        BotaoLocalizar.setText(bundle.getString("LojaAlteraUsuario.BotaoLocalizar.text")); // NOI18N

        javax.swing.GroupLayout PainelLocalizarUsuarioLayout = new javax.swing.GroupLayout(PainelLocalizarUsuario);
        PainelLocalizarUsuario.setLayout(PainelLocalizarUsuarioLayout);
        PainelLocalizarUsuarioLayout.setHorizontalGroup(
            PainelLocalizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLocalizarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelLocalizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LUsuario)
                    .addComponent(LSenhaAtual))
                .addGap(34, 34, 34)
                .addGroup(PainelLocalizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TXTSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTUsuarioBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotaoLocalizar)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        PainelLocalizarUsuarioLayout.setVerticalGroup(
            PainelLocalizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLocalizarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelLocalizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LUsuario)
                    .addComponent(TXTUsuarioBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoLocalizar))
                .addGap(18, 18, 18)
                .addGroup(PainelLocalizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LSenhaAtual)
                    .addComponent(TXTSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PainelCadastroUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PainelLocalizarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelLocalizarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTSenhaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTSenhaAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTSenhaAtualActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoGravar;
    private javax.swing.JButton BotaoLocalizar;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LRSenha;
    private javax.swing.JLabel LSenha;
    private javax.swing.JLabel LSenhaAtual;
    private javax.swing.JLabel LUsuario;
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel PainelCadastroUsuario;
    private javax.swing.JPanel PainelDados;
    private javax.swing.JPanel PainelLocalizarUsuario;
    private javax.swing.JPasswordField TXTRSenha;
    private javax.swing.JPasswordField TXTSenha;
    private javax.swing.JPasswordField TXTSenhaAtual;
    private javax.swing.JTextField TXTUsuario;
    private javax.swing.JTextField TXTUsuarioBusca;
    // End of variables declaration//GEN-END:variables
}
