
package loja.telas.jinternalframe;
import loja.botoes.LojaBotoes;

public class LojaAlteraProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form LojaCadastroProduto
     */
    public LojaAlteraProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCadastroProdutos = new javax.swing.JPanel();
        PainelBotoes = new javax.swing.JPanel();
        BotaoGravar = new javax.swing.JButton();
        BotaoExcluir = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();
        PainelCamposdados1 = new javax.swing.JPanel();
        TXTCodigo = new javax.swing.JTextField();
        TXTNome = new javax.swing.JTextField();
        TXTMarca = new javax.swing.JTextField();
        TXTModelo = new javax.swing.JTextField();
        PainelCamposdados2 = new javax.swing.JPanel();
        LDataCompra = new javax.swing.JLabel();
        LValorCusto = new javax.swing.JLabel();
        LValorUnitario = new javax.swing.JLabel();
        LQuantidade = new javax.swing.JLabel();
        TXTDataCompra = new javax.swing.JTextField();
        TXTValorCusto = new javax.swing.JTextField();
        TXTValorUnitario = new javax.swing.JTextField();
        TXTQuantidade = new javax.swing.JSpinner();
        LCodigo = new javax.swing.JLabel();
        LNome = new javax.swing.JLabel();
        LMarca = new javax.swing.JLabel();
        LModelo = new javax.swing.JLabel();
        LDescricao = new javax.swing.JLabel();
        PTXTDescricao = new javax.swing.JScrollPane();
        TXTDescricao = new javax.swing.JTextArea();
        PainelLocalizar = new javax.swing.JPanel();
        TXTCodigoB = new javax.swing.JCheckBox();
        TXTNomeB = new javax.swing.JCheckBox();
        TXTSobrenomeB = new javax.swing.JCheckBox();
        TXTModeloB = new javax.swing.JCheckBox();
        TXTBusca = new javax.swing.JTextField();
        BotaoLocalizar = new javax.swing.JButton();
        PainelTabela = new javax.swing.JPanel();
        SPTabela = new javax.swing.JScrollPane();
        TabelaResultado = new javax.swing.JTable();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("loja/telas/jinternalframe/Bundle"); // NOI18N
        PainelCadastroProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("LojaAlteraProduto.PainelCadastroProdutos.border.title"))); // NOI18N

        BotaoGravar.setText(bundle.getString("LojaAlteraProduto.BotaoGravar.text")); // NOI18N
        BotaoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGravarActionPerformed(evt);
            }
        });

        BotaoExcluir.setText(bundle.getString("LojaAlteraProduto.BotaoExcluir.text")); // NOI18N
        BotaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirActionPerformed(evt);
            }
        });

        BotaoCancelar.setText(bundle.getString("LojaAlteraProduto.BotaoCancelar.text")); // NOI18N
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelBotoesLayout = new javax.swing.GroupLayout(PainelBotoes);
        PainelBotoes.setLayout(PainelBotoesLayout);
        PainelBotoesLayout.setHorizontalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(BotaoGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BotaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        PainelBotoesLayout.setVerticalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoGravar)
                    .addComponent(BotaoExcluir)
                    .addComponent(BotaoCancelar))
                .addContainerGap())
        );

        TXTCodigo.setText(bundle.getString("LojaAlteraProduto.TXTCodigo.text")); // NOI18N
        TXTCodigo.setEnabled(false);

        TXTNome.setText(bundle.getString("LojaAlteraProduto.TXTNome.text")); // NOI18N
        TXTNome.setEnabled(false);

        TXTMarca.setText(bundle.getString("LojaAlteraProduto.TXTMarca.text")); // NOI18N
        TXTMarca.setEnabled(false);

        TXTModelo.setText(bundle.getString("LojaAlteraProduto.TXTModelo.text")); // NOI18N
        TXTModelo.setEnabled(false);

        javax.swing.GroupLayout PainelCamposdados1Layout = new javax.swing.GroupLayout(PainelCamposdados1);
        PainelCamposdados1.setLayout(PainelCamposdados1Layout);
        PainelCamposdados1Layout.setHorizontalGroup(
            PainelCamposdados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCamposdados1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCamposdados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXTCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(TXTNome)
                    .addComponent(TXTMarca)
                    .addComponent(TXTModelo))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        PainelCamposdados1Layout.setVerticalGroup(
            PainelCamposdados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCamposdados1Layout.createSequentialGroup()
                .addComponent(TXTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        LDataCompra.setText(bundle.getString("LojaAlteraProduto.LDataCompra.text")); // NOI18N

        LValorCusto.setText(bundle.getString("LojaAlteraProduto.LValorCusto.text")); // NOI18N

        LValorUnitario.setText(bundle.getString("LojaAlteraProduto.LValorUnitario.text")); // NOI18N

        LQuantidade.setText(bundle.getString("LojaAlteraProduto.LQuantidade.text")); // NOI18N

        TXTDataCompra.setText(bundle.getString("LojaAlteraProduto.TXTDataCompra.text")); // NOI18N
        TXTDataCompra.setEnabled(false);

        TXTValorCusto.setText(bundle.getString("LojaAlteraProduto.TXTValorCusto.text")); // NOI18N
        TXTValorCusto.setEnabled(false);

        TXTValorUnitario.setText(bundle.getString("LojaAlteraProduto.TXTValorUnitario.text")); // NOI18N
        TXTValorUnitario.setEnabled(false);

        TXTQuantidade.setEnabled(false);

        javax.swing.GroupLayout PainelCamposdados2Layout = new javax.swing.GroupLayout(PainelCamposdados2);
        PainelCamposdados2.setLayout(PainelCamposdados2Layout);
        PainelCamposdados2Layout.setHorizontalGroup(
            PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCamposdados2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelCamposdados2Layout.createSequentialGroup()
                        .addComponent(LDataCompra)
                        .addGap(40, 40, 40)
                        .addComponent(TXTDataCompra))
                    .addGroup(PainelCamposdados2Layout.createSequentialGroup()
                        .addGroup(PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LValorCusto)
                            .addComponent(LValorUnitario)
                            .addComponent(LQuantidade))
                        .addGap(40, 40, 40)
                        .addGroup(PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXTQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTValorUnitario, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(TXTValorCusto))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelCamposdados2Layout.setVerticalGroup(
            PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCamposdados2Layout.createSequentialGroup()
                .addGroup(PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDataCompra)
                    .addComponent(TXTDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LValorCusto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LValorUnitario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCamposdados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LQuantidade)
                    .addComponent(TXTQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        LCodigo.setText(bundle.getString("LojaAlteraProduto.LCodigo.text")); // NOI18N

        LNome.setText(bundle.getString("LojaAlteraProduto.LNome.text")); // NOI18N

        LMarca.setText(bundle.getString("LojaAlteraProduto.LMarca.text")); // NOI18N

        LModelo.setText(bundle.getString("LojaAlteraProduto.LModelo.text")); // NOI18N

        LDescricao.setText(bundle.getString("LojaAlteraProduto.LDescricao.text")); // NOI18N

        TXTDescricao.setColumns(20);
        TXTDescricao.setRows(5);
        TXTDescricao.setEnabled(false);
        PTXTDescricao.setViewportView(TXTDescricao);

        javax.swing.GroupLayout PainelCadastroProdutosLayout = new javax.swing.GroupLayout(PainelCadastroProdutos);
        PainelCadastroProdutos.setLayout(PainelCadastroProdutosLayout);
        PainelCadastroProdutosLayout.setHorizontalGroup(
            PainelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCadastroProdutosLayout.createSequentialGroup()
                        .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PainelCadastroProdutosLayout.createSequentialGroup()
                        .addGroup(PainelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PTXTDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelCadastroProdutosLayout.createSequentialGroup()
                                .addGroup(PainelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelCadastroProdutosLayout.createSequentialGroup()
                                        .addComponent(LDescricao)
                                        .addGap(227, 227, 227))
                                    .addGroup(PainelCadastroProdutosLayout.createSequentialGroup()
                                        .addGroup(PainelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LCodigo)
                                            .addComponent(LNome)
                                            .addComponent(LMarca)
                                            .addComponent(LModelo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PainelCamposdados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PainelCamposdados2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(53, 53, 53))))
        );
        PainelCadastroProdutosLayout.setVerticalGroup(
            PainelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastroProdutosLayout.createSequentialGroup()
                .addGroup(PainelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelCadastroProdutosLayout.createSequentialGroup()
                        .addComponent(LCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LDescricao))
                    .addComponent(PainelCamposdados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PainelCamposdados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PTXTDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PainelLocalizar.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("LojaAlteraProduto.PainelLocalizar.border.title"))); // NOI18N

        TXTCodigoB.setText(bundle.getString("LojaAlteraProduto.TXTCodigoB.text")); // NOI18N

        TXTNomeB.setText(bundle.getString("LojaAlteraProduto.TXTNomeB.text")); // NOI18N

        TXTSobrenomeB.setText(bundle.getString("LojaAlteraProduto.TXTSobrenomeB.text")); // NOI18N

        TXTModeloB.setText(bundle.getString("LojaAlteraProduto.TXTModeloB.text")); // NOI18N

        TXTBusca.setText(bundle.getString("LojaAlteraProduto.TXTBusca.text")); // NOI18N

        BotaoLocalizar.setText(bundle.getString("LojaAlteraProduto.BotaoLocalizar.text")); // NOI18N
        BotaoLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLocalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelLocalizarLayout = new javax.swing.GroupLayout(PainelLocalizar);
        PainelLocalizar.setLayout(PainelLocalizarLayout);
        PainelLocalizarLayout.setHorizontalGroup(
            PainelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLocalizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TXTCodigoB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTNomeB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTSobrenomeB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTModeloB)
                .addGap(24, 24, 24)
                .addComponent(TXTBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoLocalizar)
                .addGap(32, 32, 32))
        );
        PainelLocalizarLayout.setVerticalGroup(
            PainelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLocalizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTCodigoB)
                        .addComponent(TXTNomeB)
                        .addComponent(TXTSobrenomeB)
                        .addComponent(BotaoLocalizar))
                    .addGroup(PainelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTModeloB)
                        .addComponent(TXTBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        TabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Marca", "Modelo", "Valor Unitario", "QTD"
            }
        ));
        TabelaResultado.setEnabled(false);
        SPTabela.setViewportView(TabelaResultado);
        if (TabelaResultado.getColumnModel().getColumnCount() > 0) {
            TabelaResultado.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("LojaAlteraProduto.TabelaResultado.columnModel.title0")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("LojaAlteraProduto.TabelaResultado.columnModel.title1")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("LojaAlteraProduto.TabelaResultado.columnModel.title2")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("LojaAlteraProduto.TabelaResultado.columnModel.title3")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("LojaAlteraProduto.TabelaResultado.columnModel.title4")); // NOI18N
            TabelaResultado.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("LojaAlteraProduto.TabelaResultado.columnModel.title5")); // NOI18N
        }

        javax.swing.GroupLayout PainelTabelaLayout = new javax.swing.GroupLayout(PainelTabela);
        PainelTabela.setLayout(PainelTabelaLayout);
        PainelTabelaLayout.setHorizontalGroup(
            PainelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTabelaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(SPTabela)
                .addContainerGap())
        );
        PainelTabelaLayout.setVerticalGroup(
            PainelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTabelaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(SPTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelLocalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelCadastroProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PainelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PainelCadastroProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLocalizarActionPerformed
        // TODO add your handling code here:
        LojaBotoes LB = new LojaBotoes();
        LB.Localizar();
    }//GEN-LAST:event_BotaoLocalizarActionPerformed

    private void BotaoGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGravarActionPerformed
        // TODO add your handling code here:
        LojaBotoes LB = new LojaBotoes();
        LB.Gravar();
    }//GEN-LAST:event_BotaoGravarActionPerformed

    private void BotaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirActionPerformed
        // TODO add your handling code here:
        LojaBotoes LB = new LojaBotoes();
        LB.Excluir();
    }//GEN-LAST:event_BotaoExcluirActionPerformed

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        // TODO add your handling code here:
        LojaBotoes LB = new LojaBotoes();
        LB.Cancelar();
    }//GEN-LAST:event_BotaoCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoGravar;
    private javax.swing.JButton BotaoLocalizar;
    private javax.swing.JLabel LCodigo;
    private javax.swing.JLabel LDataCompra;
    private javax.swing.JLabel LDescricao;
    private javax.swing.JLabel LMarca;
    private javax.swing.JLabel LModelo;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LQuantidade;
    private javax.swing.JLabel LValorCusto;
    private javax.swing.JLabel LValorUnitario;
    private javax.swing.JScrollPane PTXTDescricao;
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel PainelCadastroProdutos;
    private javax.swing.JPanel PainelCamposdados1;
    private javax.swing.JPanel PainelCamposdados2;
    private javax.swing.JPanel PainelLocalizar;
    private javax.swing.JPanel PainelTabela;
    private javax.swing.JScrollPane SPTabela;
    private javax.swing.JTextField TXTBusca;
    private javax.swing.JTextField TXTCodigo;
    private javax.swing.JCheckBox TXTCodigoB;
    private javax.swing.JTextField TXTDataCompra;
    private javax.swing.JTextArea TXTDescricao;
    private javax.swing.JTextField TXTMarca;
    private javax.swing.JTextField TXTModelo;
    private javax.swing.JCheckBox TXTModeloB;
    private javax.swing.JTextField TXTNome;
    private javax.swing.JCheckBox TXTNomeB;
    private javax.swing.JSpinner TXTQuantidade;
    private javax.swing.JCheckBox TXTSobrenomeB;
    private javax.swing.JTextField TXTValorCusto;
    private javax.swing.JTextField TXTValorUnitario;
    private javax.swing.JTable TabelaResultado;
    // End of variables declaration//GEN-END:variables
}
