
package loja.telas.jinternalframe;


public class LojaConsultaProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form LojaConsultaProduto
     */
    public LojaConsultaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelConsultaProduto = new javax.swing.JPanel();
        PanelBotoes = new javax.swing.JPanel();
        BotaoAlterar = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();
        PanelConsulta = new javax.swing.JPanel();
        TXTCodigo = new javax.swing.JCheckBox();
        TXTNome = new javax.swing.JCheckBox();
        TXTMarca = new javax.swing.JCheckBox();
        TXTConsulta = new javax.swing.JTextField();
        BotaoConsultar = new javax.swing.JButton();
        TabelaConsulta = new javax.swing.JScrollPane();
        RetornoConsulta = new javax.swing.JTable();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("loja/telas/jinternalframe/Bundle"); // NOI18N
        PanelConsultaProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("LojaConsultaProduto.PanelConsultaProduto.border.title"))); // NOI18N

        BotaoAlterar.setText(bundle.getString("LojaConsultaProduto.BotaoAlterar.text")); // NOI18N

        BotaoCancelar.setText(bundle.getString("LojaConsultaProduto.BotaoCancelar.text")); // NOI18N

        javax.swing.GroupLayout PanelBotoesLayout = new javax.swing.GroupLayout(PanelBotoes);
        PanelBotoes.setLayout(PanelBotoesLayout);
        PanelBotoesLayout.setHorizontalGroup(
            PanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotoesLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(BotaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBotoesLayout.setVerticalGroup(
            PanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBotoesLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(PanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoAlterar)
                    .addComponent(BotaoCancelar))
                .addContainerGap())
        );

        TXTCodigo.setText(bundle.getString("LojaConsultaProduto.TXTCodigo.text")); // NOI18N

        TXTNome.setText(bundle.getString("LojaConsultaProduto.TXTNome.text")); // NOI18N

        TXTMarca.setText(bundle.getString("LojaConsultaProduto.TXTMarca.text")); // NOI18N

        TXTConsulta.setText(bundle.getString("LojaConsultaProduto.TXTConsulta.text")); // NOI18N

        BotaoConsultar.setText(bundle.getString("LojaConsultaProduto.BotaoConsultar.text")); // NOI18N

        javax.swing.GroupLayout PanelConsultaLayout = new javax.swing.GroupLayout(PanelConsulta);
        PanelConsulta.setLayout(PanelConsultaLayout);
        PanelConsultaLayout.setHorizontalGroup(
            PanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TXTCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoConsultar))
        );
        PanelConsultaLayout.setVerticalGroup(
            PanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTCodigo)
                    .addComponent(TXTNome)
                    .addComponent(TXTMarca)
                    .addComponent(TXTConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoConsultar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RetornoConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Marca", "Modelo", "QTD", "Valor"
            }
        ));
        TabelaConsulta.setViewportView(RetornoConsulta);
        if (RetornoConsulta.getColumnModel().getColumnCount() > 0) {
            RetornoConsulta.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("LojaConsultaProduto.RetornoConsulta.columnModel.title0")); // NOI18N
            RetornoConsulta.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("LojaConsultaProduto.RetornoConsulta.columnModel.title1")); // NOI18N
            RetornoConsulta.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("LojaConsultaProduto.RetornoConsulta.columnModel.title2")); // NOI18N
            RetornoConsulta.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("LojaConsultaProduto.RetornoConsulta.columnModel.title3")); // NOI18N
            RetornoConsulta.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("LojaConsultaProduto.RetornoConsulta.columnModel.title5")); // NOI18N
            RetornoConsulta.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("LojaConsultaProduto.RetornoConsulta.columnModel.title4")); // NOI18N
        }

        javax.swing.GroupLayout PanelConsultaProdutoLayout = new javax.swing.GroupLayout(PanelConsultaProduto);
        PanelConsultaProduto.setLayout(PanelConsultaProdutoLayout);
        PanelConsultaProdutoLayout.setHorizontalGroup(
            PanelConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TabelaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                    .addComponent(PanelConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelConsultaProdutoLayout.setVerticalGroup(
            PanelConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabelaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelConsultaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelConsultaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAlterar;
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoConsultar;
    private javax.swing.JPanel PanelBotoes;
    private javax.swing.JPanel PanelConsulta;
    private javax.swing.JPanel PanelConsultaProduto;
    private javax.swing.JTable RetornoConsulta;
    private javax.swing.JCheckBox TXTCodigo;
    private javax.swing.JTextField TXTConsulta;
    private javax.swing.JCheckBox TXTMarca;
    private javax.swing.JCheckBox TXTNome;
    private javax.swing.JScrollPane TabelaConsulta;
    // End of variables declaration//GEN-END:variables
}
