package loja.telas;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import loja.database.LojaLog;
//import loja.botoes.LojaBotoes;
import loja.telas.jinternalframe.*;
import loja.autentica.LojaUltimo;
public class FrmPrincipal extends javax.swing.JFrame {
    LojaLog LLOG = new LojaLog();
    LojaUltimo LUlt = new LojaUltimo();
    String UsuarioLogado;
    
    
    /**
     * Creates new form frmPrincipal
     */
    public FrmPrincipal() {
        initComponents();

    }

    LojaCadastroCliente LCC = new LojaCadastroCliente();
    LojaCadastroProduto LCP = new LojaCadastroProduto();
    LojaCadastroUsuario LCU = new LojaCadastroUsuario();
    LojaConsultaCliente LConC = new LojaConsultaCliente();
    LojaConsultaProduto LConP = new LojaConsultaProduto();
    LojaConsultaVendas LConV = new LojaConsultaVendas();
    LojaMovimentoCaixa LMC = new LojaMovimentoCaixa();
    LojaRelatorio LR = new LojaRelatorio();
    LojaAlteraCliente LAC = new LojaAlteraCliente();
    LojaAlteraProduto LAP = new LojaAlteraProduto();
    LojaAlteraUsuario LAU = new LojaAlteraUsuario();
    LojaRelatorioContasReceber LCR = new LojaRelatorioContasReceber();
    LojaVenda LV = new LojaVenda();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenuItem7 = new javax.swing.JMenuItem();
        jLabel22 = new javax.swing.JLabel();
        JDP_principal = new javax.swing.JDesktopPane();
        jMenuBar_TOP = new javax.swing.JMenuBar();
        CadastroMenu = new javax.swing.JMenu();
        CadastrarCliente = new javax.swing.JMenuItem();
        CadastrarUsuario = new javax.swing.JMenuItem();
        CadastrarProduto = new javax.swing.JMenuItem();
        AlterarCliente = new javax.swing.JMenuItem();
        AlterarUsuarioSenha = new javax.swing.JMenuItem();
        AlterarProduto = new javax.swing.JMenuItem();
        ConsultaMenu = new javax.swing.JMenu();
        ConsultaCliente = new javax.swing.JMenuItem();
        ConsultaProduto = new javax.swing.JMenuItem();
        ConsultaVendas = new javax.swing.JMenuItem();
        VendasMenu = new javax.swing.JMenu();
        VendaMercadoria = new javax.swing.JMenuItem();
        FinanceiroMenu = new javax.swing.JMenu();
        ContasReceber = new javax.swing.JMenuItem();
        RelatorioVendas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        jLabel22.setText("jLabel22");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja De Instrumentos");
        setPreferredSize(new java.awt.Dimension(1280, 720));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, JDP_principal, org.jdesktop.beansbinding.ELProperty.create("${maximumSize}"), this, org.jdesktop.beansbinding.BeanProperty.create("minimumSize"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(null);

        JDP_principal.setBackground(new java.awt.Color(255, 255, 255));
        JDP_principal.setMaximumSize(new java.awt.Dimension(1920, 1080));
        JDP_principal.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(JDP_principal);
        JDP_principal.setBounds(0, 0, 3170, 1080);

        CadastroMenu.setText("Cadastro");
        CadastroMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroMenuActionPerformed(evt);
            }
        });

        CadastrarCliente.setText("Cadastrar Cliente");
        CadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarClienteActionPerformed(evt);
            }
        });
        CadastroMenu.add(CadastrarCliente);

        CadastrarUsuario.setText("Cadastrar Usuario");
        CadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarUsuarioActionPerformed(evt);
            }
        });
        CadastroMenu.add(CadastrarUsuario);

        CadastrarProduto.setText("Cadastrar Produto");
        CadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProdutoActionPerformed(evt);
            }
        });
        CadastroMenu.add(CadastrarProduto);

        AlterarCliente.setText("Alterar Cliente");
        AlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarClienteActionPerformed(evt);
            }
        });
        CadastroMenu.add(AlterarCliente);

        AlterarUsuarioSenha.setText("Alterar Usuario/Senha");
        AlterarUsuarioSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarUsuarioSenhaActionPerformed(evt);
            }
        });
        CadastroMenu.add(AlterarUsuarioSenha);

        AlterarProduto.setText("Alterar Produto");
        AlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarProdutoActionPerformed(evt);
            }
        });
        CadastroMenu.add(AlterarProduto);

        jMenuBar_TOP.add(CadastroMenu);

        ConsultaMenu.setText("Consultar");

        ConsultaCliente.setText("Consultar Cliente");
        ConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaClienteActionPerformed(evt);
            }
        });
        ConsultaMenu.add(ConsultaCliente);

        ConsultaProduto.setText("Consultar Produto");
        ConsultaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaProdutoActionPerformed(evt);
            }
        });
        ConsultaMenu.add(ConsultaProduto);

        ConsultaVendas.setText("Consultar Vendas");
        ConsultaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaVendasActionPerformed(evt);
            }
        });
        ConsultaMenu.add(ConsultaVendas);

        jMenuBar_TOP.add(ConsultaMenu);

        VendasMenu.setText("Vendas");
        VendasMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendasMenuActionPerformed(evt);
            }
        });

        VendaMercadoria.setText("Venda de Mercadoria");
        VendaMercadoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendaMercadoriaActionPerformed(evt);
            }
        });
        VendasMenu.add(VendaMercadoria);

        jMenuBar_TOP.add(VendasMenu);

        FinanceiroMenu.setText("Financeiro");

        ContasReceber.setText("Contas a Receber");
        ContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContasReceberActionPerformed(evt);
            }
        });
        FinanceiroMenu.add(ContasReceber);

        RelatorioVendas.setText("Movimento Caixa");
        RelatorioVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioVendasActionPerformed(evt);
            }
        });
        FinanceiroMenu.add(RelatorioVendas);

        jMenuBar_TOP.add(FinanceiroMenu);

        jMenu4.setText("Ajuda");

        jMenuItem8.setText("Sobre");
        jMenu4.add(jMenuItem8);

        jMenuBar_TOP.add(jMenu4);

        setJMenuBar(jMenuBar_TOP);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void CadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarClienteActionPerformed
        try {
            //chamar classe log e gerar log que foi clicado aqui e data hora e se der algum erro guardar no log
            //usuario logado a aba que se encontra
            //LojaBotoes LB = new LojaBotoes();
            //LB.CadastroCliente();
            LLOG.GravarLog(LUlt.Ultimo(), "", "Cadastrar Cliente", "Cadastrar Cliente");
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JDP_principal.add(LCC);
        LAP.setVisible(false);
        LAC.setVisible(false);
        LAU.setVisible(false);
        LCC.setVisible(true);
        LCP.setVisible(false);
        LCU.setVisible(false);
        LConC.setVisible(false);
        LConP.setVisible(false);
        LConV.setVisible(false);
        LMC.setVisible(false);
        LR.setVisible(false);
        LCR.setVisible(false);
        LV.setVisible(false);
        

    }//GEN-LAST:event_CadastrarClienteActionPerformed

    private void CadastroMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroMenuActionPerformed
        //chamar classe log e gerar log que foi clicado aqui e data hora e se der algum erro guardar no log 
        //usuario logado a aba que se encontra

    }//GEN-LAST:event_CadastroMenuActionPerformed

    private void CadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProdutoActionPerformed
        try {
            //chamar classe log e gerar log que foi clicado aqui e data hora e se der algum erro guardar no log
            //usuario logado a aba que se encontra
            LLOG.GravarLog(LUlt.Ultimo(), "", "Cadastrar Produto", "Cadastrar produto no estoque");
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JDP_principal.add(LCP);
        LAP.setVisible(false);
        LAC.setVisible(false);
        LAU.setVisible(false);
        LCC.setVisible(false);
        LCP.setVisible(true);
        LCU.setVisible(false);
        LConC.setVisible(false);
        LConP.setVisible(false);
        LConV.setVisible(false);
        LMC.setVisible(false);
        LR.setVisible(false);
        LCR.setVisible(false);
        LV.setVisible(false);
        
    }//GEN-LAST:event_CadastrarProdutoActionPerformed

    private void VendasMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendasMenuActionPerformed
        //chamar classe log e gerar log que foi clicado aqui e data hora e se der algum erro guardar no log 
        //usuario logado a aba que se encontra         
    }//GEN-LAST:event_VendasMenuActionPerformed

    private void ConsultaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaProdutoActionPerformed
        try {
            //chamar classe log e gerar log que foi clicado aqui e data hora e se der algum erro guardar no log
            //usuario logado a aba que se encontra
            LLOG.GravarLog(LUlt.Ultimo(), "", "Consultar Produto", "Consultar se produto existe ou não");
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JDP_principal.add(LConP);
        LAP.setVisible(false);
        LAC.setVisible(false);
        LAU.setVisible(false);
        LConP.setVisible(true);
        LCC.setVisible(false);
        LCC.setVisible(false);
        LCP.setVisible(false);
        LCU.setVisible(false);
        
        LConV.setVisible(false);
        LMC.setVisible(false);
        LR.setVisible(false);
        LCR.setVisible(false);
        LV.setVisible(false);
        
    }//GEN-LAST:event_ConsultaProdutoActionPerformed

    private void VendaMercadoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendaMercadoriaActionPerformed
        try {
            //chamar classe log e gerar log que foi clicado aqui e data hora e se der algum erro guardar no log
            //usuario logado a aba que se encontra
            LLOG.GravarLog(LUlt.Ultimo(), "", "Venda Mercadoria", "Vender mercadoria para clientes");
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JDP_principal.add(LV);
        LAP.setVisible(false);
        LAC.setVisible(false);
        LAU.setVisible(false);
        LV.setVisible(true);
        LCC.setVisible(false);
        LCC.setVisible(false);
        LCP.setVisible(false);
        LCU.setVisible(false);
        LConC.setVisible(false);
        LConP.setVisible(false);
        LConV.setVisible(false);
        LMC.setVisible(false);
        LR.setVisible(false);
        LCR.setVisible(false);
        

    }//GEN-LAST:event_VendaMercadoriaActionPerformed

    private void ConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaClienteActionPerformed
        try {
            //chamar classe log e gerar log que foi clicado aqui e data hora e se der algum erro guardar no log
            //usuario logado a aba que se encontra
            LLOG.GravarLog(LUlt.Ultimo(), "", "Consulta cliente", "Consultar se cliente esta cadastrado e vereficar dados");
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JDP_principal.add(LConC);
        LAP.setVisible(false);
        LAC.setVisible(false);
        LAU.setVisible(false);
        LConC.setVisible(true);
        LCC.setVisible(false);
        LCC.setVisible(false);
        LCP.setVisible(false);
        LCU.setVisible(false);
        LConP.setVisible(false);
        LConV.setVisible(false);
        LMC.setVisible(false);
        LR.setVisible(false);
        LCR.setVisible(false);
        LV.setVisible(false);
        
    }//GEN-LAST:event_ConsultaClienteActionPerformed

    private void ContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContasReceberActionPerformed
        try {
            //chamar classe log e gerar log que foi clicado aqui e data hora e se der algum erro guardar no log
            //usuario logado a aba que se encontra
            LLOG.GravarLog(LUlt.Ultimo(), "", "Contas a receber", "Receber contas dos clientes");
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JDP_principal.add(LCR);
        LAP.setVisible(false);
        LAC.setVisible(false);
        LAU.setVisible(false);
        LCR.setVisible(true);
        LCC.setVisible(false);
        LCC.setVisible(false);
        LCP.setVisible(false);
        LCU.setVisible(false);
        LConC.setVisible(false);
        LConP.setVisible(false);
        LConV.setVisible(false);
        LMC.setVisible(false);
        LR.setVisible(false);
        LV.setVisible(false);
        
    }//GEN-LAST:event_ContasReceberActionPerformed

    private void RelatorioVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioVendasActionPerformed
        try {
            LLOG.GravarLog(LUlt.Ultimo(), "", "Relatorio de vendas", "Relatorio de vendas detalhado");
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JDP_principal.add(LMC);
        LAP.setVisible(false);
        LAC.setVisible(false);
        LAU.setVisible(false);
        LCR.setVisible(false);
        LCC.setVisible(false);
        LCC.setVisible(false);
        LCP.setVisible(false);
        LCU.setVisible(false);
        LConC.setVisible(false);
        LConP.setVisible(false);
        LConV.setVisible(false);
        LMC.setVisible(true);
        LR.setVisible(false);
        LV.setVisible(false);
        
    }//GEN-LAST:event_RelatorioVendasActionPerformed

    private void ConsultaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaVendasActionPerformed
        try {
            LLOG.GravarLog(LUlt.Ultimo(), "", "Consulta Vendas", "Consultar vendas realizadas");
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JDP_principal.add(LConV);
        LAP.setVisible(false);
        LAC.setVisible(false);
        LAU.setVisible(false);
        LCR.setVisible(false);
        LCC.setVisible(false);
        LCC.setVisible(false);
        LCP.setVisible(false);
        LCU.setVisible(false);
        LConC.setVisible(false);
        LConP.setVisible(false);
        LConV.setVisible(true);
        LMC.setVisible(false);
        LR.setVisible(false);
        LV.setVisible(false);
        
    }//GEN-LAST:event_ConsultaVendasActionPerformed

    private void CadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarUsuarioActionPerformed
        try {
            LLOG.GravarLog(LUlt.Ultimo(), "", "Cadastrar Usuario", "Cadastrar usuario para uso do sistema");
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JDP_principal.add(LCU);
        LAP.setVisible(false);
        LAC.setVisible(false);
        LAU.setVisible(false);
        LCR.setVisible(false);
        LCC.setVisible(false);
        LCC.setVisible(false);
        LCP.setVisible(false);
        LCU.setVisible(true);
        LConC.setVisible(false);
        LConP.setVisible(false);
        LConV.setVisible(false);
        LMC.setVisible(false);
        LR.setVisible(false);
        LV.setVisible(false);
        
    }//GEN-LAST:event_CadastrarUsuarioActionPerformed

    private void AlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarClienteActionPerformed
        try {
            LLOG.GravarLog(LUlt.Ultimo(), "", "Alterar Cliente", "Alterar dados do cliente");
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JDP_principal.add(LAC);
        LAP.setVisible(false);
        LAC.setVisible(true);
        LAU.setVisible(false);
        LCR.setVisible(false);
        LCC.setVisible(false);
        LCC.setVisible(false);
        LCP.setVisible(false);
        LCU.setVisible(false);
        LConC.setVisible(false);
        LConP.setVisible(false);
        LConV.setVisible(false);
        LMC.setVisible(false);
        LR.setVisible(false);
        LV.setVisible(false);
        
    }//GEN-LAST:event_AlterarClienteActionPerformed

    private void AlterarUsuarioSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarUsuarioSenhaActionPerformed
        try {
            LLOG.GravarLog(LUlt.Ultimo(), "", "Alterar Usuario/Senha", "Alterar Usuario/Senha do usuario");
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JDP_principal.add(LAU);
        LAP.setVisible(false);
        LAC.setVisible(false);
        LAU.setVisible(true);
        LCR.setVisible(false);
        LCC.setVisible(false);
        LCC.setVisible(false);
        LCP.setVisible(false);
        LCU.setVisible(false);
        LConC.setVisible(false);
        LConP.setVisible(false);
        LConV.setVisible(false);
        LMC.setVisible(false);
        LR.setVisible(false);
        LV.setVisible(false);

    }//GEN-LAST:event_AlterarUsuarioSenhaActionPerformed

    private void AlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarProdutoActionPerformed
        try {
            LLOG.GravarLog(LUlt.Ultimo(), "", "Alterar produto", "Alterar produto");
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JDP_principal.add(LAP);
        LAP.setVisible(true);
        LAC.setVisible(false);
        LAU.setVisible(false);
        LCR.setVisible(false);
        LCC.setVisible(false);
        LCC.setVisible(false);
        LCP.setVisible(false);
        LCU.setVisible(false);
        LConC.setVisible(false);
        LConP.setVisible(false);
        LConV.setVisible(false);
        LMC.setVisible(false);
        LR.setVisible(false);
        LV.setVisible(false);
        
    }//GEN-LAST:event_AlterarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlterarCliente;
    private javax.swing.JMenuItem AlterarProduto;
    private javax.swing.JMenuItem AlterarUsuarioSenha;
    private javax.swing.JMenuItem CadastrarCliente;
    private javax.swing.JMenuItem CadastrarProduto;
    private javax.swing.JMenuItem CadastrarUsuario;
    private javax.swing.JMenu CadastroMenu;
    private javax.swing.JMenuItem ConsultaCliente;
    private javax.swing.JMenu ConsultaMenu;
    private javax.swing.JMenuItem ConsultaProduto;
    private javax.swing.JMenuItem ConsultaVendas;
    private javax.swing.JMenuItem ContasReceber;
    private javax.swing.JMenu FinanceiroMenu;
    private javax.swing.JDesktopPane JDP_principal;
    private javax.swing.JMenuItem RelatorioVendas;
    private javax.swing.JMenuItem VendaMercadoria;
    private javax.swing.JMenu VendasMenu;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar_TOP;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
